### ISSUE TITLE
Searching for single digits in an article replaces characters in e-mail addresses and highlights them.

### ISSUE THREAD

**Issue by marvelade** [splitbrain/dokuwiki#1128] opened 2015-04-30 09:30 UTC
A search in the search box for a single digit gets you a search result page. When you click one of the search results you get on the article page with an adapted URL that tells PHP which strings to highlight through the s[] GET variable:

http://mywebserver/mywiki/doku.php?id=articlename&s[]=1

When there are e-mail addresses in that page, something strange happens to them: the s[]=1 replaces replaces all a's with "1;" so for example the the address "email@domain.com" comes out as "em1;il@dom1;in.com"

![screen shot 2015-04-30 at 11 28 10](https://cloud.githubusercontent.com/assets/1527929/7410080/04eef902-ef2c-11e4-8562-562d0f1f2fc0.png)

dokuwiki source:

![screen shot 2015-04-30 at 11 29 31](https://cloud.githubusercontent.com/assets/1527929/7410110/336493d2-ef2c-11e4-98c7-d96d359d07d8.png)

Same deal for:

2 : replaces all b's and r's with "2;"
3 : replaces all c's and s'es (both upper and lower case) with "3;"
4 : replaces all t's with "4;" ()

**Comment by splitbrain** [comment] 2015-05-02 08:38
What's your setting for the ```mailguard``` option?

**Comment by selfthinker** [comment] 2015-05-03 11:30
I can confirm this issue. I get the same result in a vanilla installation.

**Comment by selfthinker** [comment] 2015-05-03 16:58
I guess this is related: [FS#2321](https://bugs.dokuwiki.org/index.php?do=details&task_id=2321) and [FS#2651](https://bugs.dokuwiki.org/index.php?do=details&task_id=2651), therefore it's also a duplicate of #992.

It is the same issue as the HTML for the buggy search result looks like this:
```
...&#x6d;&#x6<span class="search_hit">1</span>;&#x69;...
```

**Comment by selfthinker** [comment] 2015-05-03 17:00
Closing as it's a duplicate (#992).

**Closed by selfthinker** 2015-05-03 17:00 UTC
Labels: Bug
