### ISSUE TITLE
WRAP Plugin not working on Release rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by Paddy4711** [splitbrain/dokuwiki#3133] opened 2020-06-04 09:18 UTC
Hi all,
we successfully upgraded via the upgrade manager the DW to Hogfather.

Since we experience troubles with the WRAP plugin. The Issue is that the boxes are not shown anymore.

Once we disable/uninstall the plugin and activate/reinstall the plugin, the first call of a page shows the boxes like normal, but on a reload the boxes have diapered. No way to restore the boxed just the mentioned steps help but only once.

We cleared the cache with (http://www.example.com/namespace/page?purge=true) but again the works only once.

Not sure if the issue is related to the "cache" issue other users reported?

Anyway, again thanks for your support !!!

Best regards,
Patrick

**Comment by splitbrain** [comment] 2020-06-04 12:37
Could be related to #3129 but I can not reproduce the problem. It's working fine here. Can you give a list of all other installed plugins?

**Comment by Peyje** [comment] 2020-06-04 15:39
I've got the same exact problem, very strange behavior. I tried deactivating various extensions to no avail. Here is a list of mine:

- Add New Page by Benjamin Santalucia and others
- edittable plugin by Andreas Gohr
- newpagetemplate Plugin by Jason Grout and others
- nspages plugin by Guillaume Turri
- Pageimage by lisps and others
- Pagelist Plugin by Matthias Schulte and others
- Tag Plugin by Michael Hamann
- Wrap Plugin by Anika Henke

Funny thing is, the only diff between the correct page and the faulty page (looking at the .html here) is that the lines corresponding to the Wrap Plugin are blank (not missing!), in my case only one line:
`<div class="wrap_clear plugin_wrap"></div>`

**Comment by joerghuettinger** [comment] 2020-06-05 08:06
Its also the tabbox plugin which shows the same behaviour:
- preview looks good
- when saved, the page looks fine
- after the first reload, it looks like all the styling is gone

Cleaning conf/userstyle.css and resetting style.ini did not change anything.
Maybe there is something both tabbox and wrap plugin have in common?

**Comment by phy25** [comment] 2020-06-05 12:33
@joerghuettinger What other plugin do you have? Could yoi disable them and try again? Id it's still happening could you create an issue here https://github.com/cosmocode/dokuwiki-plugin-tabbox/issues ?

**Comment by joerghuettinger** [comment] 2020-06-06 15:07
It looks like  ~~NOCACHE~~  causes the problems. Disabling all other plugins did not help.

**Comment by phy25** [comment] 2020-06-07 20:52
This should have been fixed by #3132. Could we try again with that patch, or by directly using master branch to verify?

**Comment by Peyje** [comment] 2020-06-07 22:04
I just updated my instance to the newest possible snapshot (627b135e7b4b684410fcbf33c5112feb34c416a9) and that fixes it for me! Thank you very much. :+1: 

@joerghuettinger While \~\~NOCACHE\~\~ does not seem to be the underlying problem, a problem with caching was referenced in #3132, so this fix might very well solve it for you as well, hopefully.

**Closed** 2020-06-07 22:07 UTC
Labels: duplicate

**Comment by joerghuettinger** [comment] 2020-06-08 08:44
Thank you, the master branch did the job. Great!
