### ISSUE TITLE
Make Notifications Smarter

### ISSUE THREAD

**Issue by Ryonez** [splitbrain/dokuwiki#3186] opened 2020-06-24 03:03 UTC
At the moment, I maintain two dokuwiki installations. And currently, dokuwik is releasing "release candidates" (rc) versions.
 Because I'm on stable, this means I get this:
![image](https://user-images.githubusercontent.com/16157130/85493495-1b887c80-b62b-11ea-852b-3d8d0ef37248.png)

To resolve this, I'm going to propose two solutions.

1. Make notifications dismissible.

2. Only show update notifications for the selected "branch" in settings. For me, I only want stable updates, I don't care for rc releases.

**Comment by phy25** [comment] 2020-06-24 03:17
1. Not sure why the initial implementation doesn't have it.
2. Duplicate of #3144.

**Comment by Ryonez** [comment] 2022-07-25 00:11
Wow. Two years later I'm back as this is still an issue.

**Closed** 2022-07-25 04:45 UTC
Labels: won't fix

**Comment by Ryonez** [comment] 2022-07-25 05:00
I would ask for this to be reconsidered.

Admins for the site are forced to have this banner unless they update, which is not always desired.

**Comment by splitbrain** [comment] 2022-07-29 15:20
Since this keeps popping up again and again, I will quickly quote myself from a recent forum post:

> What do you think makes a release more stable than a release candidate? Serious question.
>
> It's not like we intentionally publish unstable release candidates. A release candidate is a version of DokuWiki that works perfectly fine for the developers. We see absolutely nothing wrong with it. In fact I run it on dokuwiki.org without problems.
> 
> But that does not mean it's ready to be called a stable release. DokuWiki is used by thousands of users around the world in various environments. Without those users trying an RC we won't find out whats wrong.
>
> So yes, I absolutely encourage everyone to upgrade to an RC. In the worst case something breaks, you report it and you have to wait a couple of weeks until a fixed release is available. If you don't run the RC and something breaks, you might have to wait a year or more for the next release.
>
> PS: personally I wouldn't bother with RCs anymore (see https://www.patreon.com/posts/why-we-dont-do-8173276) but sometimes we do one anyway.

So, no. I won't differentiate between release candidates and releases in the notifications. If you don't like it, disable the update check completely, but don't come back here to complain about bugs in releases. That's on you then.

Also keep in mind that update notifications are only shown to superusers.
