### ISSUE TITLE
PHP embedded webserver can't serve page with a dot in the name.

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3165] opened 2020-06-11 16:24 UTC
Hi,

Because PHP has a strange behaviour with requests that have a dot in the name, it cannot serve pages whose name has a dot.

How to reproduce. 

1.  `php -S 127.0.0.1:8000 index.php`
2. point your browser to http://localhost:8000/this.is.broken

**Comment by phy25** [comment] 2020-06-11 16:55
What error message do you see? Do you expect PHP to use htaccess config? What about localhost:8000/index.php/this.is.broken?

**Comment by schplurtz** [comment] 2020-06-11 20:27
on my laptop, I run my own personal wiki with `php -S 127.0.0.1:8000 index.php`

I use `$conf['userewrite'] = '1';` (as stated in index.php itself). This works great. pages, media, plugins, templates, forms... Everything just works so great.

But as soon as you use a pagename with a dot : 
- php produces an empty answer
- As already written, no error at all : 
  - The php commands prints no error, just
    ```
    DW-engine (0) $ php -S 127.0.0.1:8000 index.php
    [Thu Jun 11 22:05:38 2020] PHP 7.4.6 Development Server (http://127.0.0.1:8000) started
    [Thu Jun 11 22:05:43 2020] 127.0.0.1:49217 Accepted
    [Thu Jun 11 22:05:43 2020] 127.0.0.1:49217 Closing
    ```
  - No error in the navigator, just an empty page.

To answer your last question `http://localhost:8000/index.php/this.is.broken` works. But it is useless. If I create a page with this syntax `[[:this.is.broken]]`, it won't create such a link.

**Comment by splitbrain** [comment] 2020-06-11 20:42
Seems to be caused by this bug: https://bugs.php.net/bug.php?id=61286 which has been closed as won't fix. There seem to be some work arounds... I'll investigate.

**Comment by schplurtz** [comment] 2020-06-12 05:17
Thanks for the quick reaction.

This brings an unexpected behaviour with `http://127.0.0.1:8000` or `http://127.0.0.1:8000/`. Previously, it would load the start page, now it tries to load  the page index.php. Actually, `http://127.0.0.1:8000/index.php` does not run index.php but loads the page named index.php.

**Comment by phy25** [comment] 2020-06-13 22:18
I would still point `/index.php` to that exact page rather than the start page, but the root part should be fixed somehow.

**Closed** 2020-07-13 11:56 UTC
Labels: Bug
