### ISSUE TITLE
<code bash> and <file bash foo> adds a "&nbsp;" to the code.

### ISSUE THREAD

**Issue by benks-io** [splitbrain/dokuwiki#3422] opened 2021-02-24 12:04 UTC
When code is defined as "bash" in code or file tags, for every empty line there is a `&nbsp;` in the code. When no language is set there is no such char. When copied and pasted to a command line oder script (e.g. via vim), this invisible char leads to unexpected behavior.
Is there a way to adjust that?

**Comment by gerardnico** [comment] 2021-05-20 15:11
Not in the last dokuwiki.

Input:
```
<code bash>
cat $file;
</code>
```
Output:
```html
<pre class="code bash"><span class="kw2">cat</span> <span class="re1">$file</span>;</pre>
```

**Comment by benks-io** [comment] 2021-05-20 16:52
@gerardnico For every emtpy line it is:

Input:

```
<code bash>
cat $file1;

cat $file1;
</code>
```

Output:
```
<pre class="code bash"><span class="kw2">cat</span> <span class="re1">$file1</span>;
&nbsp;
<span class="kw2">cat</span> <span class="re1">$file2</span>;</pre>
```

**Comment by gerardnico** [comment] 2021-05-20 17:13
Ah ok.  I see !

The highlighting in Dokuwiki occurs in the `code` function of the `XHTML` class.
Precisely here: https://github.com/splitbrain/dokuwiki/blob/stable/inc/parser/xhtml.php#L699

[Geshi](http://qbnz.com/highlighter/) is used. If this is only for `bash`, there is a problem with Geshi.

As a temporary solution, you can  modify the code or use a plugin that takes over the `code` component
https://www.dokuwiki.org/plugins?plugintag=code#extension__table

Personally, I have developed one with prism:
https://combostrap.com/ui/code

**Comment by schplurtz** [comment] 2021-08-24 06:56
This is a duplicate of #2614

**Closed** 2021-09-06 08:55 UTC
