### ISSUE TITLE
Fetch.php randomly fails to retrieve images and pdfs

### ISSUE THREAD

**Issue by gravitoon** [splitbrain/dokuwiki#2474] opened 2018-08-16 16:54 UTC
I upgraded Dokuwiki to 2018-04-22a "Greebo". I am currently using Mac OS X Server El Capitan 10.11.6. I had to install a new version of php on server to make the upgrade work and point in apache to the new php module - /Library/Server/Web/Config/apache2/http_server_app.config. However when people try and download pdfs -or view them, sometimes it reports then as being 0 size. If I relink the pdfs I get inconsistent results -sometimes it works and other times it does not. Images sometimes display and other times do not. Any ideas? What is the latest version of dokuwiki that does not require php 5.6. I upgraded the wiki via the upgrade plugin.

**Comment by Michaelsy** [comment] 2018-09-28 23:51
Other environment but similar symptom is reported here:
https://forum.dokuwiki.org/thread/16300

**Comment by splitbrain** [comment] 2018-09-29 07:01
Is this a duplicate of #2466?

**Comment by Michaelsy** [comment] 2018-09-29 07:28
> Is this a duplicate of #2466?

At least for the case I could reproduce (see https://forum.dokuwiki.org/thread/16300), this also affects very small files (PNG image 20 x 20). Is this the answer to your question? (Probably negative in this case.)

I see parallels in that it obviously depends on internal conditions of the server. The problem is therefore not always reproducible.

**Comment by Michaelsy** [comment] 2018-09-29 07:34
More details about @gravitoon 's case you could read here: https://forum.dokuwiki.org/thread/16164

**Comment by Michaelsy** [comment] 2018-10-23 06:53
Possibly same issue: https://forum.dokuwiki.org/thread/16380

**Comment by Michaelsy** [comment] 2018-10-23 07:43
@Andi
At the moment there is a live demo on a page where the problem occurs. It is with 1&1 again. The same symptom as I noticed. The image-result of this code is not shown (at Firefox 52.9.0):

    {{wiki:dokuwiki-128.png?20}}

Can you please take a look at that?: http://www.wikikanin.de/doku.php?id=wiki:wiki

Additionally: https://forum.dokuwiki.org/thread/16380

**Comment by peterfromearth** [comment] 2018-10-24 18:59
I had a further look into it. The issue is a php warning 
`Warning: A non-numeric value encountered in /homepages/9/d151672064/htdocs/Wikikanin/inc/common.php on line 1675` with greebo a
```php
function php_to_byte($v) {
    $l   = substr($v, -1);
    $ret = substr($v, 0, -1);
    switch(strtoupper($l)) {
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'P':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'T':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'G':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'M':
            $ret *= 1024;
        /** @noinspection PhpMissingBreakStatementInspection */
        case 'K':
            $ret *= 1024;
            break;
        default;
            $ret *= 10; //line 1675
            break;
    }
    return $ret;
}
```
the callstack is `php_to_byte(trim(ini_get('memory_limit')))` 

it seems that `ini_get('memory_limit')` returns something different than expected. 

maybe someone else with the issue can deliver more debug information with `var_dump(ini_get('memory_limit'))`


someone with the issue will see also the php warning by doing the `do=check` call.

**Comment by Michaelsy** [comment] 2018-10-25 08:30
I have now made for this issue its own DokuWiki installation on my 1&1 account. Fortunately, the error occurs there: http://ts-imagescaling.informantum.de

I'm ready to give @Andi the access data for the server if he so wishes.

**Comment by igittigitt** [comment] 2018-10-26 13:20
I use 1&1 hoster for my Wiki also. I found that using PHP up to 7.0 works fine, and as soon as i change PHP-Version above, like 7.1 or 7.2 i get no images shown at all, once i'm into the pageditor (regardless of hitting preview or save). So it maybe depend on the PHP version...

**Comment by phy25** [comment] 2018-10-26 15:54
Interesting: `?do=check` doesn't cause the warning, while `fetch.php` causes the warning on http://ts-imagescaling.informantum.de/.

They have some difference: `trim` included or not. So it's better to debug it further, maybe by inserting `var_dump(ini_get('memory_limit'))` in fetch.php?

https://github.com/splitbrain/dokuwiki/blob/879d2b08ea80562b2c649cc70c70831f126674e4/inc/infoutils.php#L136-L147

https://github.com/splitbrain/dokuwiki/blob/879d2b08ea80562b2c649cc70c70831f126674e4/inc/common.php#L1887-L1892

**Comment by Michaelsy** [comment] 2018-10-26 17:57
@phy25 FYI: Maybe you should know there is a `php.ini` file with following content:

    error_reporting = E_ALL | E_STRICT;
    log_errors = On;
    display_errors = Off;
    error_log = /kunden/homepages/18/d150228280/htdocs/subs/ts-imagescaling/php-errors.log;

Without this file the `?do=check` option produces warnings in the HTML output.

**Comment by peterfromearth** [comment] 2018-10-26 18:03
found it, this is a known bug and already fixed by #2420

og from the forum posted the output of ini_get('memory_limit') === "-1"
https://forum.dokuwiki.org/thread/16382

**Comment by peterfromearth** [comment] 2018-10-26 18:21
the issue of not showing the pictures is because the multiplication in php_to_byte throws an error. When display_errors is on -  the webserver delivers the warning text and the unscaled image, which can not be correctly shown. If display_errors is off php_to_byte returns 0 which results in delivering only the unscaled image. 
So as a workaround on can either:
- set display_errors = off (which should be the case in a production environment)
- use image magick lib (admin config im_convert https://www.dokuwiki.org/config:im_convert)

**Comment by Michaelsy** [comment] 2018-10-26 18:31
I have now done the following:
1. `php.ini` removed
2. Patch corresponding to: https://github.com/splitbrain/dokuwiki/pull/2420/files

Result:
1. Scaled image is shown.
2. The warnings in the `do=check `output persist.

**Comment by Michaelsy** [comment] 2018-10-26 18:51
And now I have done the following:
1.  php.ini used again.
2. The patch removed.

Result: Scaled image is still displayed.
I've already experienced such a disappearance of the problem.

**Comment by Michaelsy** [comment] 2018-10-26 19:05
And now I have done the following:
1.  `php.ini` removed again.

Result: Scaled image is still displayed.

**Comment by peterfromearth** [comment] 2018-10-26 20:04
the PR #2556 fixes the warnings in `do=check` 
@Michaelsy once the scaled image is in the cache, the scaling is not done anymore. This is why it still worked after you removed the patch.

**Comment by Michaelsy** [comment] 2018-10-26 20:29
> @Michaelsy once the scaled image is in the cache, the scaling is not done anymore. This is why it still worked after you removed the patch.

No. I checked it. Browser cache emptied. Dokuwiki-cache emptied (which probably has nothing to do with it) and for security the website called even on another computer that has never visited this website.

Currently the basic state is set without patch. So you can try it yourself.

**Comment by Michaelsy** [comment] 2018-10-26 20:40
@peterfromearth 
Ok, you seem to be right somehow. As a last test, I have now taken another image file. That is actually not displayed again.

In which cache did the first image file survive ???

**Comment by peterfromearth** [comment] 2018-10-26 20:43
@Michaelsy it is definitely the dokuwiki file cache in data/cache/

**Comment by Michaelsy** [comment] 2018-10-26 21:05
@peterfromearth You are right.

Considering this knowledge, I come to the conclusion that with the patch #2420 I can eliminate the problem with the scaled images at 1&1 (at least on a "phenomenal level", without having really understood the technical issue).

**Comment by igittigitt** [comment] 2018-10-26 21:15
I also tried to add the php.ini to the htdocs dir, but it had no effect, no php-error.log was created.
You can see the effect only when editing a page, because the resized images where delivered from Dokuwikis filecache. Simply hit edit and preview on an page to reproduce the issue.
BUT, once more, the problem with the images occurs only if you choose a PHP version > 7.0 (at 1&1 hosting you can set this per subdomain), so there must be some changes. Maybe it's worth looking at the PHP changelogs...

**Comment by Michaelsy** [comment] 2018-10-26 21:20
@igittigitt: You should apply these patch: https://github.com/splitbrain/dokuwiki/pull/2420/files

**Comment by igittigitt** [comment] 2018-10-26 21:30
Yes, this works for me as well! Now could set PHP to 7.2, like it should these days :-)

**Comment by igittigitt** [comment] 2018-10-26 21:48
The images are gone because they where'nt delivered from Dokuwiki. If you start the Webdebugger in Chrome you can see that the answer of the load-request for the image contains an errormessage instead of the imagedata.
Because ini_get('memory_limit') returns "-1" instead of any value (which means memory is 'unlimited') the sub php_to_byte() does not find a size-label (like 'K' or 'M' or such) and uses default. There it tries to multiply substr('-1', 0, -1), which result to '-', by 10, which fail, of course, and procude the error.
The funny part of this is, that i excpeted the setting of memory_limit changes when choosing another PHP-Version than 7.0, but it did'nt.

**Comment by pdaire** [comment] 2019-01-14 21:22
@Michaelsy the patch worked great for me! Thanks.
Sadly for regular users of DokuWiki and 1&1ionos this patch is not included in the bundled versions you install with 1click. I had to edit the file directly in the hosting file manager web system.

**Closed** 2019-01-14 22:11 UTC

**Comment by Michaelsy** [comment] 2019-01-14 22:48
> this patch is not included in the bundled versions you install with 1click

The patch is also not included in the latest official release 2018-04-22b Greebo which was published on January 6, 2019.

**Comment by phy25** [comment] 2019-01-14 23:31
It's in master, but not in stable. Not sure whether this is worth a patch release. (Actually the current stable branch's unit test is failing; if new patch gets released please also have a look at that.)
