### ISSUE TITLE
Plugin blog is not working with master any more

### ISSUE THREAD

**Issue by LarsGit223** [splitbrain/dokuwiki#2297] opened 2018-04-03 18:38 UTC
With DokuWiki master it is not possible to create new blog entries using the blog plugin. After clicking on ```Create this page``` the error message ```Failed to handle action: preview``` appears.

**Comment by splitbrain** [comment] 2018-04-11 13:46
Normally I'd say this should be reported in the the blog plugin's issue tracker but since it might be related to the new action router I had a deeper look:

There's something weird in the blog plugin:

https://github.com/dokufreaks/plugin-blog/blob/108c756ea17268b5b7886b9eda26d35132157a77/action.php#L112-L117

It does **return** new values for `$ACT` instead of setting `$ACT` or `$event->data`. I'd argue that is wrong, but seems to have been supported before?

Docs on [ACTION_ACT_PREPROCESS](https://www.dokuwiki.org/devel:event:action_act_preprocess) do not mention anything about the handler's return value...

**Comment by Klap-in** [comment] 2018-04-11 13:52
That function is not a handler. The function is called to set `$event->data` in the actual handler.

See: 
https://github.com/dokufreaks/plugin-blog/blob/108c756ea17268b5b7886b9eda26d35132157a77/action.php#L31

**Comment by splitbrain** [comment] 2018-04-11 14:27
Thanks @Klap-in I missed that.

The problem is at https://github.com/dokufreaks/plugin-blog/blob/108c756ea17268b5b7886b9eda26d35132157a77/action.php#L98-L99. The plugin prevents the default handling but says that the `preview` action should be used. Removing that line makes the plugin work again.

I'm unsure why the line is there. I commented the line and checked out the stable branch and it still seems to work.

Annotate points to https://github.com/dokufreaks/plugin-blog/issues/59 which was fixed by @michitux 

However, since this action component does not really do anything than setting an ID and then calling either `edit` or `preview` modes I wonder why it ever wanted to call `preventDefault()` at all?

The fact remains that `ACTION_ACT_PREPROCESS` seems to work slightly different now. The question is: should we try to adjust it? Or is this a weird fluke?

**Comment by LarsGit223** [comment] 2018-04-11 15:45
> The problem is at https://github.com/dokufreaks/plugin-blog/blob/108c756ea17268b5b7886b9eda26d35132157a77/action.php#L98-L99. The plugin prevents the default handling but says that the preview action should be used. Removing that line makes the plugin work again.

I have also played around with the default action flag but oversaw that line, so I thought it might be a problem with the new action router.

> The fact remains that ACTION_ACT_PREPROCESS seems to work slightly different now. The question is: should we try to adjust it? Or is this a weird fluke?

So, if I understood it correctly, ```preview``` is the default action for ```preview``` and that (of course) will not work if the default action is disabled via ```$event->preventDefault();```. That sounds like the old action code had a bug/little flaw which made this wrong code in the blog plugin work. Therefore I vote for changing the line in the blog plugin and see if it works everywhere. If not we can still make an version dependant adjustment in the blog plugin. But changing it in the DokuWiki core seems to introduce inconsistency in my eyes (on a just re-designed part, not nice).

**Comment by michitux** [comment] 2018-04-11 16:06
Basically all important (?) code of the old preview action is duplicated in the blog plugin with some additional template handling code. Therefore, the default action didn't need to be called anymore but only the template part was required. However, at least in the stable branch I think removing the `preventDefault` wouldn't hurt as the default action already checks if `$TEXT` is already set so nothing should happen.

**Comment by splitbrain** [comment] 2018-04-12 07:47
So consensus is, we fix the blog plugin by removing the `preventDefault()` and keep the ActionRouter as is?

**Comment by Klap-in** [comment] 2018-04-12 11:29
I understand that the blog plugin can be fixed with the proposed fix. Fine so far.

However, I do not understand which behaviour is changed. Could someone explain what he/she thinks what has changed?

**Comment by Klap-in** [comment] 2018-04-12 11:47
My first guess (if I read the conversation):
If you change the `$ACT` (by modifying `$event->data`):
Then before the refactoring you need to call 'preventDefault()' and still the new `$ACT` is performed.
After the refactoring, the `$ACT`  (changed to another action) is only performed if no 'preventDefault()' is called?

But if I look at the code, this does not match with my description.
Or the storing of 'preview' in the `Plugin()` object should make a difference?

**Comment by michitux** [comment] 2018-04-12 11:59
@Klap-in The old code did not perform the action. It just rendered the template of the action. I.e., in the case of the preview action, `act_preview` was not called.

@splitbrain I think there is nothing wrong with changing the blog plugin, but I have not yet looked at the new code to see if anything should be changed.

**Comment by LarsGit223** [comment] 2018-04-12 15:36
@splitbrain: Yes from my side.

**Comment by splitbrain** [comment] 2018-04-14 07:13
I updated the blog plugin.

**Closed by splitbrain** 2018-04-14 07:13 UTC
Labels: Needs Feedback/Discussion

**Comment by LarsGit223** [comment] 2018-04-14 08:32
Thanks.
