### ISSUE TITLE
The plugin repository could not be contacted on Windows - select_stream problem

### ISSUE THREAD

**Issue by gerardnico** [splitbrain/dokuwiki#3474] opened 2021-04-12 09:01 UTC
If you have installed Dokuwiki on Windows.

You will get the following message:
```txt
The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings.
```

Why ?
Because the HTTP Client makes use of the function [select_stream](https://www.php.net/manual/en/function.stream-select.php) to check a timeout as we can seen [here](https://github.com/splitbrain/dokuwiki/blob/master/inc/HTTP/HTTPClient.php#L588)

```php
// wait for stream ready or timeout (1sec)
if (@stream_select($sel_r, $sel_w, $sel_e, 1) === false) {
	usleep(1000);
	continue;
}
```

The problem is that the function [select_stream](https://www.php.net/manual/en/function.stream-select.php) returns always `false` as stated in the documentation:

```txt
Note: Windows compatibility
Use of stream_select() on file descriptors returned by proc_open() will fail and return false under Windows.
```

The timeout kick-in and we get the faulty error message.

Solution:
  * On Windows, don't use this. 
  * I have deleted all 3 `stream_select` timeout block and it works like a charm

**Comment by gerardnico** [comment] 2021-04-12 10:37
Just discovered that there is a [isWindows](https://github.com/splitbrain/dokuwiki/blob/master/inc/init.php#L536) function that may help

**Comment by splitbrain** [comment] 2021-04-12 15:12
We're not using stream_select on a proc_open stream but on a network stream. I manage many Windows setups during my day job and the HTTP client works fine - so it's not a general Windows problem. Simply removing this code is not a proper solution and likely will cause broken downloads occasionally.

The first step would be to provide additional data to find out what goes wrong on your system.

**Comment by gerardnico** [comment] 2021-04-12 16:04
You lost me with `proc_open`. I didn't knew that it was a php thing.

I got the following warning from the `select_stream` call:

```txt
stream_select(): unable to select [2]: No such file or directory (max_fd=508)
```

It seems that `max_fd` is an acronym for `max file descriptor` then I thought that the number of open file was reached and that the `select_stream` was checking the number of open file and returning false because it couldn't get one.

I have tried with Php:
  * `php-5.6.9-Win32-VC11-x64`
  * `php-5.6.9-nts-Win32-VC11-x64`

And the `select_stream` function returns always `false`

Thanks

**Comment by gerardnico** [comment] 2021-04-12 16:07
Windows version 10 (20H2 - OS Build 19042.867), it's a dev laptop.

This code works without any problem.

```php
$filename = "http://www.dokuwiki.org/lib/plugins/pluginrepo/api.php?q=dw2pdf&fmt=yaml";
$handle = fopen($filename, "rb");
$http = stream_get_contents($handle);
fclose($handle);
var_dump($http);
```

**Comment by gerardnico** [comment] 2021-04-12 16:35
This code does not work if I let the `select_stream` loop. I got a `Timeout while reading headers (15.009s)` error.

```php
$http = new \dokuwiki\HTTP\DokuHTTPClient();
$http->debug = 1;
$http->get('http://www.dokuwiki.org/lib/plugins/pluginrepo/api.php?q=sqlite&fmt=yaml');
var_dump($http);
```

**Comment by splitbrain** [comment] 2021-04-14 13:41
Can you reproduce the problem on a more modern PHP (eg. 7.4)?

**Comment by gerardnico** [comment] 2021-04-14 13:51
Yeah. It works in 7.4.6. 
I have no idea why.
I have installed 5.6 because this is the lowest supported php of Dokuwiki.

**Comment by gerardnico** [comment] 2021-04-14 13:52
7.2.28 works also.

**Comment by gerardnico** [comment] 2021-04-14 13:53
I don't have any other locally php version to test.

**Comment by phy25** [comment] 2021-04-14 20:09
We have already removed all unit tests for PHP 5.6: https://github.com/splitbrain/dokuwiki/blob/4ee6ddae660f9ec72c1f6e2ddb72d6b29d6d8900/.github/workflows/testLinux.yml#L13

Should we make it official that PHP 5.6 is no longer supported?

**Comment by splitbrain** [comment] 2021-04-15 06:54
@phy25 it's already official: 3f874cb39717289bf80a160faf3083588c3d4311 only the current stable still supports 5.6

@gerardnico I will close this as won't fix for above reason

**Closed by splitbrain** 2021-04-15 06:54 UTC
Labels: requires more info

**Comment by gerardnico** [comment] 2021-04-15 07:03
@splitbrain I'm on the stable.

This code is also on the stable.
https://github.com/splitbrain/dokuwiki/blob/stable/inc/HTTP/HTTPClient.php#L589

I have got to the official documentation before installing:
https://www.dokuwiki.org/requirements
And it states that 5.6 is supported.

I would understand that you would not fix this but it should be stated at minimum somewhere
that 5.6. is no more supported.

**Comment by splitbrain** [comment] 2021-04-15 08:58
@gerardnico current stable runs fine on 5.6 (though I would not recommend it) and as far as I know you're the only one having this problem. Even if we would develop a fix or workaround for the problem, it would only be released with the next DokuWiki version. But since this new version will not support 5.6 anymore it would be futile to implement a fix for something that can not be reproduced on newer php versions.

**Comment by gerardnico** [comment] 2021-04-15 09:07
@splitbrain Yeah I got that. I should have been more specific over what I wanted. 

I have updated already [the requirement documentation](https://www.dokuwiki.org/requirements)
```
Php 5.6 will not be supported in the next release and has some [[github>splitbrain/dokuwiki/issues/3474|quirk on Windows]], we recommend to use at minimal from now on the version 7.2.
```

This is just that we lost already too much time on it and I don't want anybody to get into the same problem (prevention).

If you are ok with this change, I will let it otherwise I can change it.

**Comment by mckaygerhard** [comment] 2021-05-31 20:33
this is windosh*t only problem.. most production servers are unix type anyway so i dont think limit php to 7 is solution.. development tools also stills supports 5.6 so there's no sense in limiting

**Comment by gerardnico** [comment] 2021-06-02 19:17
> i dont think limit php to 7 is solution.. 
This is not limiting, this is just seen as `not worse to do` because the next Dokuwiki release will not support it. If you get the problem, change the code manually or upgrade to a most recent version.

**Comment by mckaygerhard** [comment] 2021-06-02 20:11
> > i dont think limit php to 7 is solution..
> 
> @mckaygerhard This is not limiting, this is just seen as `not worse to do` because the next Dokuwiki release will not support the version 5.6 anymore. If you get the problem, change the code manually or upgrade to a most recent version.

maybe the only reference in wiki are made by you about supporting 5.6.. and is a windo only related problem

**Comment by gerardnico** [comment] 2021-06-03 12:22
@mckaygerhard Sorry but I didn't get what you want. Did you get this problem ? Can i help you ?


Note: The php version 5.6 is also end of life since [31 Dec 2018](https://www.php.net/eol.php) which means that most of the installations should have been upgraded.
