### ISSUE TITLE
Newlines inserted when copying code

### ISSUE THREAD

**Issue by tuxayo** [splitbrain/dokuwiki#2838] opened 2019-08-09 15:53 UTC
Hi, given the following wikicode

```
  echo "some commands"
```

or

```
<code>
echo "some commands"
</code>
```

- select by triple click
- paste in a text editor
- Firefox only: notice that a newline was inserted before the command
- Firefox and Chromium: notice that a newline was inserted after the command

This causes commands being immediately run when being pasted which can leads to issues.

Can someone reproduce?

**Comment by tuxayo** [comment] 2019-08-09 15:55
mitigation: select by clicking and dragging the mouse across the line instead of triple clicking. Which is less convenient a not very practical with long line which have a scroll-bar.

**Comment by phy25** [comment] 2019-08-09 16:34
What's your OS? I can reproduce this at https://www.dokuwiki.org/playground:issue2838, only in Windows 10 Chrome 76. Cannot reproduce it in Windows Firefox, IE, Edge.

Triple-click select is a browser dependent feature, so when implementation varies, behaviors can be a lot more different. According to https://github.com/ckeditor/ckeditor-dev/issues/484, and mainly https://github.com/w3c/selection-api/issues/70, there is no standard about this across browsers. Also I believe it's a tricky part (converting rich HTML to plain text) about the `\n` at the end of the copied content.

I tend to close this issue because this is not really the fault of the webpage. Even if we fix this on DokuWiki itself somehow (adapting user's triple-click behavior), the whole other internet is still being affected. This is really what every terminal user should know as a security precaution (and what browsers should fix). The only thing I think we can do, is adding JavaScript copy feature on the front end with [plugin:clippy](https://www.dokuwiki.org/plugin:clippy) or something similar.

**Comment by tuxayo** [comment] 2019-08-14 08:53
Happens in Solus Linux and Xubuntu 18.04
(I'm doing more tests)

**Comment by phy25** [comment] 2019-08-15 17:53
I can reproduce this on Safari, Firefox, and Chrome on macOS.

Once again, I tend to close this issue due to the reason mentioned before.

**Closed** 2020-01-19 18:23 UTC
Labels: Category: CSS XHTML JS Browsers, Doku Plugin idea, won't fix
