### ISSUE TITLE
Error while installing plugins from zip

### ISSUE THREAD

**Issue by do2ih** [splitbrain/dokuwiki#2361] opened 2018-04-29 19:27 UTC
When I try to install plugins using the extension manager I get an error: “Unable to identify extension directory, you need to download and install manually”. The error only occurs, when the plugin is a zip-file. No problem if you install a plugin from a tarball. It seems like the problem is located in vendor/splitbrain/php-archive. If I substitute this with the correspondending directory in old-stable everything seems to work fine.

**Comment by splitbrain** [comment] 2018-04-30 10:55
I can not reproduce this. Which plugin did you try to install. What's your environment?

**Comment by do2ih** [comment] 2018-04-30 14:53
My environment is a VM from Bitnami. With oldstable (2017-02-19e) I had no problems. After a update to the new stable (2018-04-22) the reported problem occurs. One of the plugins with the error message is the "Todo"-Plugin. Others have the same Problem. Look here: https://community.bitnami.com/t/cannot-install-plugins-in-version-20180422-0/57187

I hope, this was helpful for you.

**Comment by splitbrain** [comment] 2018-05-01 08:10
I was able to reproduce this in a bitnami image. The problem is related to this bug report: https://bugs.php.net/bug.php?id=44096

Which turns out to be a setup error of the underlying iconv system. The used codepage is missing. This should probably be fixed on the bitnami images as it makes the iconv library pretty useless.

I found a hint on how to fix this in this commit: https://github.com/phpmyadmin/phpmyadmin/commit/985bdd11abce22f2d01b9ce707b0a1e647b9d31e and implemented it in https://github.com/splitbrain/php-archive/commit/a46f3aaeb9f123fdb7db4e192b0600feebf7f773 tagged a 1.0.10 on the php-archive library.

**Closed** 2018-05-01 08:11 UTC
