### ISSUE TITLE
Meta description and footnotes

### ISSUE THREAD

**Issue by eilko** [splitbrain/dokuwiki#2383] opened 2018-05-12 13:34 UTC
When I use a footnote in the first sentences of a page using the standard  double parentheses the meta description of that page only shows the first word of the footnote.

Eg. at https://www.altaplana.be/en/dictionary/passage-le

`====== Passage mural (le) ======
{{:photos:mural_brussel:dyn003_original_378_720_pjpeg_2564269_b3df8d86c4b1a68df0b42611c0a0c7fe.jpeg?nolink&300 |Le Passage mural}}
**Le Passage** / De Doorgang is a mural by [[en:dictionary:schuiten-francois|François Schuiten]]. It was inaugurated in [[en:dictionary:1995|August 1995]] and can be found at [[en:dictionary:marche-au-charbon|Rue Marché au Charbon - Kolenmarkt]] in [[en:dictionary:brussels|Brussels]], just opposite the police station. Its area is about 20 m². Realization by G. Oreopoulos and D. Vandegeerde of society "Art Mural" ((See: http://www.ebru.be/Other/Strips/bruxelles-1000-mur-bd-passage.html)).`

gives:

`<meta name="description" content="See:" />`

**Comment by Michaelsy** [comment] 2018-05-13 07:26
> just the standard syntax

Yes, for footnotes, but for footnotes only. (Your footnotes - so far I can see - works.)
 
What do you mentioned above is to take the footnote in a meta-tag of your HTML-page. This surely is not a standard function of DokuWiki.

**Comment by eilko** [comment] 2018-05-13 07:38
No, the meta tag is based on the meta data of the page. That DokuWiki  meta data contains only "See:". It is fine for me when DokuWiki ignores everything between the double parentheses.

**Comment by eilko** [comment] 2018-05-13 07:40
It expected to see that the meta data instead of "See:"  was "Le Passage / De Doorgang is a mural by François Schuiten. It was inaugurated in August 1995 and can be found at Rue Marché au Charbon - Kolenmarkt in Brussels, just opposite the police station. Its area is about 20 m². Realization by G. Oreopoulos and D. Vandegeerde of society "Art Mural". " or something a bit shorter.

**Comment by Michaelsy** [comment] 2018-05-13 07:56
OK, I understand. But for generating your meta data you must do it with a plugin. The DokuWiki core generates no meta description - so far I know. (An other potential is your template generates the meta data description itself.)

**Comment by Michaelsy** [comment] 2018-05-13 08:53
You assume the misfunction is caused through the footnote function?

I think the misfunction is caused through the software which places the meta data in the HTML code. And this software is not a part of the Dokuwiki core.

**Comment by eilko** [comment] 2018-05-13 18:57
the meta description tag in html is based on the abstract field in de meta file of a page. This meta file has already the wrong data. So yes, I assume that the footnote function is the cause of the wrong behaviour of the abstract field in the meta file and so giving the wrong output for the meta description and every other field that is based on the abstract meta field.

**Comment by Michaelsy** [comment] 2018-05-13 21:49
Ok, I can reproduce the bug as you described it. What I found out until now: The footnote is only one of at least two conditions to arise the bug. Later more...

**Comment by Klap-in** [comment] 2018-05-14 07:34
The footnote should (already) not be recorded in the abstract: 
https://github.com/splitbrain/dokuwiki/blob/7a371ad48872e8a22314d3ecda74aeadc443e9d5/inc/parser/metadata.php#L212-L234

abstract is stored as description:
https://github.com/splitbrain/dokuwiki/blob/7a371ad48872e8a22314d3ecda74aeadc443e9d5/inc/parser/metadata.php#L100-L107

**Comment by Michaelsy** [comment] 2018-05-14 07:56
I reported the bug detailed in #2387.

**Comment by Klap-in** [comment] 2018-05-14 08:54
Normally the `cdata()` should be used for writing text to the `$this->doc`.
That function also counts the number of characters added. 
(not sure why for example links are directly writing to  `$this->doc`. Is it intentional to skip the counter?)

However: In the footnote the content of the `doc` attribute is temporary stored, and `doc` is emptied. But the counter, stored in `captured` attribute is not reset.

https://github.com/splitbrain/dokuwiki/blob/7a371ad48872e8a22314d3ecda74aeadc443e9d5/inc/parser/metadata.php#L118-L132

So if in the footnote the `cdata()` method is used, this counter increases further, and if the limit is reached, it toggles the `capture` boolean. The case in the bug report is about 250 characters.
By toggling the `capture` boolean, the  `footnote_close()` will never restore the original `doc`.

https://github.com/splitbrain/dokuwiki/blob/7a371ad48872e8a22314d3ecda74aeadc443e9d5/inc/parser/metadata.php#L228-L230

**Comment by Michaelsy** [comment] 2018-05-14 09:26
@eilko Please take a look at the [meta plugin](https://www.dokuwiki.org/plugin:meta).
1. It could be a temporaly workaround (non tested by me)
2. Maybe it could be the better method to explicitly define the description-Tag. I would prefer that - just my 5 cents!

@Klap-in Sorry, I could not really follow you, because I have nearly none of PHP expertise.

**Comment by eilko** [comment] 2018-05-14 11:28
@Michaelsy thanks for the tip. But I have over 50 pages affected by this issue and over 3000 pages at the site. Too many to handle manually.

**Comment by Michaelsy** [comment] 2018-05-15 05:16
This bug is already reported in #1250.

**Comment by Chris--S** [comment] 2018-05-16 11:39
No idea why it was marked as difficulty complex.  Should be resolved in #2390

**Comment by Chris--S** [comment] 2018-05-16 16:36
With the fix in #2390, the above wiki content now results in an abstract string of "====== Passage mural (le) ====== [Le Passage mural] Le Passage / De Doorgang is a mural by François Schuiten. It was inaugurated in August 1995 and can be found at Rue Marché au Charbon - Kolenmarkt in Brussels, just opposite the police station. Its area is about 20 m². Realization by G. Oreopoulos and D. Vandegeerde of society “Art Mural".  

Which doesn't seem entirely correct.  I'm not sure why the heading format string is present, but presumably that is another issue.

**Comment by Chris--S** [comment] 2018-05-16 16:41
My mistake.  In copy/pasting I lost the proper line ending.  Once restored, the heading is correctly interpreted, giving an abstract of "_Passage mural (le)

[Le Passage mural] Le Passage / De Doorgang is a mural by François Schuiten. It was inaugurated in August 1995 and can be found at Rue Marché au Charbon - Kolenmarkt in Brussels, just opposite the police station. Its area is about 20 m². Realization by G. Oreopoulos and D. Vandegeerde of society “Art Mural” ._"

**Closed** 2018-05-17 07:14 UTC
Labels: Bug
