### ISSUE TITLE
Search/Collation  limitations when using non-ASCII scripts, or extended Latin

### ISSUE THREAD

**Issue by disk0x** [splitbrain/dokuwiki#2037] opened 2017-07-01 18:41 UTC
Version: 2017-02-19b

When running a wiki in a language that uses extended Latin (eg French), or non-Latin scripts (eg Greek), the indexing (including collation) and search function has the following two limitations

1. Accented and not-accented versions of the same character are not treated as equivalent. For example "é" and "e" (French), or "έ" and "ε" are not treated as the same character for indexing and search purposes, even though that is the expected behaviour for speakers of those languages. 

2. In extended Latin, and non-ASCII alphabets, capital and lowercase letters are not treated as equivalent, while in basic ASCII they are. For example in Greek, the search function cannot find "Εντός" if search for "εντός" (Ε-ε are the upper/lowercase pair). 

Those two limitations in combination, also resort to collation being wrong, as dokuwiki collates all accented characters before non-accented ones.

For example, in Greek, dokuwiki gives:

> Άλφα
> Έψιλον
> Βήτα
> Γάμμα
> Δέλτα

and not the correct

> Άλφα
> Βήτα
> Γάμμα
> Δέλτα
> Έψιλον

Another report of the issue I found while looking for workarounds: https://forum.dokuwiki.org/thread/3892

**Comment by disk0x** [comment] 2018-02-11 17:53
This is still a problem in the 2017-02-19e release. 
Anyone running a development snapshot and can check if its still an issue there?

**Comment by Klap-in** [comment] 2018-02-11 20:46
Sorry, but I have no idea how I could reproduce your case?
What is this list? are these pagenames? or just text in on a page, or text on more pages?

Is it possible to provide a recipe for how I could see your case in my wiki? Thanks!

**Comment by disk0x** [comment] 2018-02-12 05:54
Thanks for replying. 

Those can be page titles, listed in the results of [tagfilter](https://www.dokuwiki.org/plugin:tagfilter), which is one of the occasions where collation happens (another occasion would be the sitemap, if and only iff unicode URLS are used, because the sitemap sorts by filename, not title page)

1. Create a few pages with titles such as 

> Άλφα
> Βήτα
> Γάμμα
> Δέλτα
> Έψιλον

2. Tag them with `{{tag>test}}`

3. Add a new page under the same namespace with
`{{tagfilter>Tag=test&sort}}`

The order displayed should be the order in the quotation, but instead what we get is the accented characters before the rest of the alphabet: 

> Άλφα
> Έψιλον
> Βήτα
> Γάμμα
> Δέλτα

* * * 

The search part of the problem is easier to replicate and it doesn't involve plugins: 

1. Create a page with the title Άλφα.
2. Search _Αλφα_, or _άλφα_, or _αλφα_

You will not get any hits.

Ά, Α, ά, α should be treated as the same character for collation and search purposes.

**Comment by moisesbr-dw** [comment] 2020-05-03 05:59
This issue has two separate parts: collation (word order, e.g. in page lists) and search.
I'm working on a collation fix in my fork.
Until now I was able to fix the index, backlinks, media management, quick search (when inserting a link during page edit) and order of search results.

In a nutshell, this is the rationale I'm following:
- If package "intl" is not loaded, sort the same way as before.
- Otherwise, create a Collator object with the locale set in conf['lang'] and use it to sort.

My tests use esperanto (conf['lang'] = 'eo'), where the collation is the following:
a b c ĉ d e f g ĝ h ĥ i j ĵ k l m n o p r s ŝ t u ŭ v z
Without the Collator object, the letters with diacritics are sorted after z.

**Comment by disk0x** [comment] 2020-05-03 09:26
That's great to hear! I can't code in PHP, but I can test your patches and contribute collation rules for other languages.

**Comment by moisesbr-dw** [comment] 2020-05-03 22:37
Of course thorough testing will be quite appreciated, thank you.

Here are some preliminary tests to check how good is the implementation of the ICU library in PHP and how we could use it in the right way.
Change the extension to .php before running.
Don't forget to enable package "intl".
For your information: my PHP here is version 7.4.2.

First, the list of all locales in the library.
A very long and complete list.
[all-locales.txt](https://github.com/splitbrain/dokuwiki/files/4571777/all-locales.txt)

Then, the list of Collator objects created with Dokuwiki locales.
The locales taken from the Collator object (valid and actual) are compared to the Dokuwiki locale.
The "good" cases are in green and the possible "bad" cases are in red.
[collators-for-dokuwiki-locales.txt](https://github.com/splitbrain/dokuwiki/files/4571783/collators-for-dokuwiki-locales.txt)

Let's take a closer look on red cases.

"eu" (Basque), "ia" (Interlingua), "la" (Latin) and "mg" (Malagasy) don't have specific collators.
The library gives a generic collator for these languages, using the "root" (default) locale.
I don't know if this is the correct answer.
If these languages use a default A to Z order, that would be fine.

The collator obtained with "de-informal" (informal German) does not use locale "de", but rather "de__".
As the actual locale of the collator is "root", the same when "de" (German) is used, I think this case is a false negative.

Norway has two official languages, "nb" (Bokmal) and "nn" (Nynorsk).
Dokuwiki uses "no" (Norwegian), but this is the name of the language group (macrolanguage) containing Bokmal and Nynorsk in ISO 639.
The library gives a collator for "nb", that is, Bokmal.
I don't know if it also works for Nynorsk.

Finally, "zh-tw" (Chinese for Taiwan) creates a collator with locale "zh_Hant_TW".
This means Chinese (zh) with Han traditional writing (Hant) in Taiwan (TW).
All right.

Another case worth looking is "ms" (Malay).
As far as I know, Malay is written with latin letters, like Indonesian.
The translation is Dokuwiki uses arabic letters, maybe used in Brunei or elsewhere.
As the collator given actually uses locale "root", it uses normal A to Z sort, which may not be useful for arabic letters.

At last, here are two tests to show the correct code to implement a natural sort.
[collator-for-esperanto.txt](https://github.com/splitbrain/dokuwiki/files/4571785/collator-for-esperanto.txt)
[collator-for-esperanto2.txt](https://github.com/splitbrain/dokuwiki/files/4571787/collator-for-esperanto2.txt)

I still have a TODO list.
When the list is over, I will drop a post here.
Stay tuned :-)

**Comment by splitbrain** [comment] 2020-05-04 16:15
@moisesbr-dw thanks for working on this. A few things to note:

We try to work as well as possible on limited PHP setups. So fallbacks when no intl extension is available should be provided. Lowercasing is usually handled by mb_string but falls back to our own implementation which is based on conversion tables (see inc/Utf8/tables/*). Greek should be covered there so I am surprised that your second example isn't working correctly.

If your first example is true (users expecting to have "é" and "e" to be treated the same when searching) of which I am not sure, then we could probably use our methods of romanization.

If you want to provide any code, please do so as a pull request based upon current master and be sure to include unit tests.

**Comment by moisesbr-dw** [comment] 2020-05-04 17:42
Hi @splitbrain ,

> We try to work as well as possible on limited PHP setups. So fallbacks when no intl extension is available should be provided.

That's what I'm doing.
But I found some glitches that deserve a fix even in the fallback code.

For example, the search() function in "search.php" does a natsort() over the page names without a previous call to utf8_decodeFN().
In the default setting, this means that "%xx%yy" (URL encoding) would be compared to normal letters, always giving a wrong sort order.

> Lowercasing is usually handled by mb_string but falls back to our own implementation which is based on conversion tables (see inc/Utf8/tables/*). Greek should be covered there so I am surprised that your second example isn't working correctly.
> 
> If your first example is true (users expecting to have "é" and "e" to be treated the same when searching) of which I am not sure, then we could probably use our methods of romanization.

I guess you're talking about disk0x's examples.

In my opinion, deaccentation and romanization should be avoided.
Deaccented page names always give wrong sort order in languages where diacritics create NEW letters, not accented ones, as is the case in Spanish (ñ), Esperanto (ĉ ĝ ĥ ĵ ŝ ŭ), maybe Czech, Polish and others.
Romanization could also create a similar problem.

> If you want to provide any code, please do so as a pull request based upon current master and be sure to include unit tests.

Any references for unit tests in PHP?
And how you run them with DokuWiki code?
I'm not that fluent on PHP, but I'm trying to learn it.

Thank you for your attention on this issue.

**Comment by splitbrain** [comment] 2020-05-04 18:30
Have a look at https://www.dokuwiki.org/devel:unittesting for unit testing

**Comment by moisesbr-dw** [comment] 2020-05-22 14:21
Good news!
I've fixed all cases of alphabetical sort: all screens, Remote API, feed, bundled plugins and all else.
Details here: [ALL_CASES.txt](https://github.com/splitbrain/dokuwiki/files/4668519/ALL_CASES.txt)

Unit testing is still missing, I'll work on that before submitting a pull request.

@disk0x : If you want to start your tests, please download [my fork](https://github.com/moisesbr-dw/dokuwiki).

**Comment by disk0x** [comment] 2020-05-22 17:37
> @disk0x : If you want to start your tests, please download [my fork](https://github.com/moisesbr-dw/dokuwiki).

Thanks for your work! I set up a testing instance (may not share link in public comments), and I think I am missing something, because I don't see a change in sort behaviour: https://imgur.com/PQQosnw.png

Just to see if I am doing anything obviously wrong:

```
$ git status
# On branch sort-with-collator
[...]
```
The dokuwiki interface language is set to English, but switching it to Greek also didn't change anything

php-intl-7.2.31

**Comment by moisesbr-dw** [comment] 2020-05-22 18:03
@disk0x Are you using a plugin?
No plugin was changed, except the bundled ones (present in the core code).

After creating some pages and media, click the sitemap link, use the search box, ask for the backlinks of a page, browse the media manager, create links on a page and look the quick search...
Everything should be sorted.

Possible caveat: all my tests were done with config "useheading" = "Never".

**Comment by moisesbr-dw** [comment] 2020-05-25 16:42
@splitbrain , I need some advice.

After fixing all sort code in the DokuWiki core (see previous messages), I attempted to look at the search problem. There are 3 crucial points:
1. inc/indexer.php, line 60: strlen() - this function counts bytes, not characters, so every latin letter with an accent is miscounted and put in the wrong index file, because the UTF-8 representation uses 2 bytes, not 1.
2. inc/Search/Indexer.php, line 798: array_search() - this function looks for an exact match in the index.
3. inc/Search/Indexer.php, line 811: preg_grep() - this function looks for part of a word in the index, but the part given in the regular expression will be an exact match.

If the DokuWiki search engine worked only with exact matching, I would already have a working solution that only fixes point 2 above, providing a carefully configured collator for matching.

But things are not like this, and there is no way AFAIK to use regular expressions and collation at the same time, solving point 3.

A working solution, then, should do the following:
* When indexing, the words must be *normalized* (deaccented etc.) before put in the index files.
* When searching, the query must be normalized before being compared to the index, so exact or partial search would work with no modification in points 2 and 3 above.

This implementation:
* would not be backward-compatible (we would increment the INDEXER_VERSION);
* could use the Normalizer class, or use romanization as a fallback.

As this seems more complicated then the sort solution already developed, I ask you (and @disk0x ) if this could be treated in another issue, so we could close this one when the sort fixing is approved.

**Comment by phy25** [comment] 2020-05-25 16:52
Just FYI I think there is ongoing work on refactoring FulltextIndex in #2943.

> when the sort fixing is approved

Not quite sure about this. Is there a PR?

**Comment by moisesbr-dw** [comment] 2020-05-25 17:26
> Just FYI I think there is ongoing work on refactoring FulltextIndex in #2943.

That's good news!

> > when the sort fixing is approved
> 
> Not quite sure about this. Is there a PR?

Not yet.
I did the necessary [changes](https://github.com/splitbrain/dokuwiki/files/4668519/ALL_CASES.txt) but have not provided unit tests yet.

Thank you for your attention on this issue.

**Comment by disk0x** [comment] 2020-05-25 17:58
Sorry, currently can't test more, I will return to this in the next two days to answer to your questions and allow things to move forward.

**Comment by moisesbr-dw** [comment] 2020-05-30 05:44
When configuration option "useheading" is "Navigation Only" or "Always", the sort order should be by page *title* instead of by page *name,* but it does not happen.
These are the affected pages:
* Sitemap
* Backlinks
* Search
  * Matching pagenames
  * Quicklinks (suggested links when typing)
  * via Remote API

It seems a separate issue to me, so I'm not working on this point in my fork.

**Comment by moisesbr-dw** [comment] 2020-06-01 21:36
@splitbrain @phy25 @disk0x  Pull request #3115

**Comment by moisesbr-dw** [comment] 2020-06-04 04:06
[Help wanted](https://forum.dokuwiki.org/d/17871-help-wanted-does-your-native-language-has-separate-letters-with-accents) for this issue!

**Closed** 2020-08-26 08:06 UTC
Labels: Category: Backend

**Comment by moisesbr-dw** [comment] 2020-08-26 21:23
As this issue is not really fully closed, I created a new issue to tackle the search part.
