### ISSUE TITLE
Missing mbstring dependency causes broken links after upgrading to Hogfather

### ISSUE THREAD

**Issue by CyanBlob** [splitbrain/dokuwiki#3113] opened 2020-06-01 16:53 UTC
Hey everyone!

I just recently upgraded to Hogfather from version 18, and now see that I've got broken links throughout my wiki.

After looking into it, I realized that in the previous version, links such as [[players:bruce]] and [[players:Bruce]] would link to the same page (case insensitive). Now, however, they point to different pages.

Additionally, links like [[places:Bruce's Library]] are now broken as well, requiring me to change them to [[places:bruce_s_library]]. It seems that links must now match the "sanitized" page names instead of the actual name.

Was something changed with how link locations are resolved?

**Comment by CyanBlob** [comment] 2020-06-01 22:45
Here's a screenshot showing the issue:
![link_issue](https://user-images.githubusercontent.com/5949523/83462013-bc6e8800-a42f-11ea-91d9-c72658bee71a.png)

**Comment by drabels** [comment] 2020-06-02 04:44
Just experienced precisely the same issue today attempting to upgrade from Greebo to Hogfather.  Reverting to Greebo and then deleting the cache files let's me continue my work (i.e. Wiki links are now functional again), but it would be good to understand what's causing the problem in this release.

**Comment by Klap-in** [comment] 2020-06-02 06:57
Sounds like a broken or missing pieces in the download package, at the first sight. 

How did you perform the upgrade? which package or which approach?

**Comment by splitbrain** [comment] 2020-06-02 08:29
I can not reproduce this either and I am a bit stumped how this should even happen. In addition to the things @Klap-in asked about, please also give info about this:

* operating system and filesystem used
* any settings related to links (camelcase, autoplural, etc.)
* installed plugins that might influence link handling
* PHP version
* if the mbstring PHP extension is available

**Comment by spamik** [comment] 2020-06-02 12:41
Happend to me as well. mbstring extension was missing, after installing it and restarting apache it seems it's working. Well, without one exception - I had some links like this: [[somens:somepage:]] which resulted in link [[somens:somepage:start]]. Now if I leave this the whole link disappear from page. If I rewrite it to [[somens:somepage:start]] it works.

**Comment by CyanBlob** [comment] 2020-06-02 15:19
I can confirm that @spamik's solution fixed the issue for me as well! I followed the instructions [here](https://www.knowledgebase-script.com/kb/article/how-to-enable-mbstring-in-php-46.html) to install it.

For the record, I upgraded to Hogfather from the Dokuwiki Upgrade plugin. This was on Raspbian 9 (ARM, on a Raspberry Pi) on an ext4 filesystem with PHP 7.0.

**Comment by CyanBlob** [comment] 2020-06-02 15:21
Did Hogfather introduce a dependency on mbstring? Or could the upgrade process have removed it?

**Comment by mjlush** [comment] 2020-06-02 19:55
I'm getting this (Raspbian buster PHP 7.3.11-1~deb10u1)
It's a strange bug.. I have a link text as
[[nu-men:The Tabley Big Table of Connections]]
but in the page is rendered as
nu-men:the_tabley_Big_table_of_Connections

I'd be willing to provide a login to my system via teamviewer

**Comment by splitbrain** [comment] 2020-06-02 19:58
I found the problem. For some reason the conversion table was missing a whole bunch of characters. Not sure what happend there. We'll have a fix out soon.

**Comment by drabels** [comment] 2020-06-03 01:15
I can confirm that installing mbstring fixed the issue for myself as well.  I'm using Debian 10 and php 7.3.  I just ran "apt-get install php-mbstring" and then restarted apache2.  Then I upgraded dokuwiki via the plugin.  All good now!

**Comment by phy25** [comment] 2020-06-03 05:01
I believe this should have been fixed in master/snapshot by https://github.com/splitbrain/dokuwiki/commit/0884c254723c9fa99e70acf920c59d7f3dbcab55, if you would like to give it a try.

Do we keep this open until a new RC is released, or until the fix is verified on `master`?

**Comment by Sperows** [comment] 2020-06-03 13:15
Had same issue on CentOS Linux release 7.8.2003 (Core), installed mbstring and it started to work.

**Comment by phy25** [comment] 2020-06-03 15:45
I am going to close this issue since it should have been fixed in RC2. Please comment if it still does not work for you in RC2.

**Closed by phy25** 2020-06-03 15:45 UTC
Labels: Bug

**Comment by CyanBlob** [comment] 2020-06-03 17:02
I upgraded to RC2, removed mbstring, and restarted Apache. I can confirm that RC2 is working as expected! Thanks for the quick turnaround everyone!

**Comment by mjlush** [comment] 2020-06-03 20:08
I've just updated toRelease rc2-2020-06-01 "Hogfather" RC2 and all is back to normal 

Thanks for the quick fix!
