### ISSUE TITLE
Problems with Bootstrap 3 Theme after update from Greebo to Hogfather

### ISSUE THREAD

**Issue by TalusUnheil** [splitbrain/dokuwiki#3131] opened 2020-06-03 20:45 UTC
Hey there! Today I updated from Greebo to Hogfather and since then I've had a few problems:

1. Worst: I can't access the Admin-/ Settings-/ User-Panel anymore. The icons dw__admin, dw__tool and dw__user_menu in the header-navbar (dw__navbar_items) are still clickable, but nothing happens if I click them. I'd like to change back to default theme until this is fixed - how can I do that?

1. The Table of contents is now 100% the width of the content

1. There is no more space/ margin between dw__title and dw__tagline in the header

These are the first things I noticed. Should I add additions here, or start new issues? cc @giterlizzi

**Comment by phy25** [comment] 2020-06-03 20:47
Duplicate of https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/483. Please address styling issues on the theme issue tracker.

**Closed by phy25** 2020-06-03 20:47 UTC

**Comment by TalusUnheil** [comment] 2020-06-03 20:54
Whoa, such fast feedback :+1: As giterlizzi is already informed, maybe the DokuWiki folks can help me with switching to default theme without accessing the Admin-Panel?

**Comment by phy25** [comment] 2020-06-03 20:58
I remember that issue include options of upgrading the theme to develop version and manually change a option. Please read it or seek help on forum.dokuwiki.org.

Please still create an issue in the theme issue tracker if you see something not right and hasn't been mentioned.
