### ISSUE TITLE
Upload of existing file not possible

### ISSUE THREAD

**Issue by zufalls** [splitbrain/dokuwiki#1863] opened 2017-02-22 12:21 UTC
It is not possible to upload a file, if it's already exists.

Version: 2017-02-19a

Browser: I would say: any, tested with Firefox 51.0.1

Workaround/Bugfix (original line with comments, my line beneath):
lib/media.php:307
    $res = media_save(
        array('name' => $path,
            'mime' => $mime,
            'ext'  => $ext),
        $ns.':'.$id,
        //(($INPUT->get->str('ow') == 'checked') ? true : false),
        (($INPUT->get->str('ow') == 'true') ? true : false),
        $auth,
        'copy'

lib/scripts/fileuploaderextends.js:326
        params = params || {};
        params['qqfile'] = name;
        //params['ow'] = jQuery('.dw__ow').attr('checked');
        params['ow'] = jQuery('.dw__ow').is(':checked');
        var queryString = qq.obj2url(params, this._options.action);

I hope this helps, maybe there is a better way to fix this, but in my installation, it works.

**Comment by zufalls** [comment] 2017-02-22 12:31
Way to reproduce:
- Open Media Manager
- Upload a file
- Try to upload the same file with set the "overwrite file, if already exist"-checkbox
- There should a appear an error message, that the file already exists

**Comment by mprins** [comment] 2017-02-22 12:49
Duplicate of #1855

**Closed** 2017-03-01 09:28 UTC
Labels: Bug, ToDo: has patch
