### ISSUE TITLE
The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings.

### ISSUE THREAD

**Issue by tonybaldwin** [splitbrain/dokuwiki#1711] opened 2016-10-05 13:31 UTC
I can, reach dokuwiki.org finr from my browser, and, on the server in question (over ssh), I can ping it all day long without losing a single packet.
However, when, on the server it does take a bit long to load dokuwiki in lynx.
There are no proxy settings on the server to be looked at.

**Comment by polyzen** [comment] 2016-10-05 15:13
Duplicate of #1407?

**Comment by splitbrain** [comment] 2016-10-14 13:45
closed in favor of #1407

**Closed by splitbrain** 2016-10-14 13:45 UTC
