### ISSUE TITLE
[BUG] Problem with media manager, insufficient rights on chrome browser

### ISSUE THREAD

**Issue by Neurozone** [splitbrain/dokuwiki#2909] opened 2019-11-13 10:39 UTC
Hello.
I've encountered a curious bug on chrome:
![image](https://user-images.githubusercontent.com/5229035/68755753-3d3b7300-0609-11ea-8a6d-750fe7930f69.png)

the user is superadmin an can't upload any file on the media manager with chrome
It works fine with firefox or waterfox

The issue is with the line 1803 on the media.php file in the inc folder
error message is:  "Sorry, you don't have enough rights to upload files."

The error is only on chrome browser

php version : PHP 7.3.10 (cli) (built: Sep 24 2019 12:36:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies

OS version: Red Hat Enterprise Linux Server release 6.10 (Santiago)

web server version: apache 2.2.15

dokuwiki version : 2018-04-22b "Greebo"

**Comment by Neurozone** [comment] 2019-11-13 11:00
On chrome:
$auth: 1 
AUTH_UPLOAD: 8

others browsers:
$auth: 255 
UPLOAD: 8

**Comment by phy25** [comment] 2019-11-13 14:36
Could you please check what cookie it has in Chrome? I am afraid the cookie is not working inside the popup (because of headers) ..?

**Comment by Neurozone** [comment] 2019-11-13 15:36
Maybe you have found the issue
On chrome:
![image](https://user-images.githubusercontent.com/5229035/68778601-b354cf80-0633-11ea-8d2d-88951aa577c3.png)

On waterfox:

![image](https://user-images.githubusercontent.com/5229035/68778652-c1a2eb80-0633-11ea-9d28-32652969ac9d.png)

**Comment by phy25** [comment] 2019-11-13 18:12
I am not sure why you have duplicate entries in waterfox. Could you please double check that those duplicate cookies has a different domain/path or not?

I am afraid that your server config prevents cookies from generating properly but without much debug info I don't know.

**Comment by Neurozone** [comment] 2019-11-19 15:20
The server is an apache out of the box

**Comment by phy25** [comment] 2020-01-19 18:27
I am closing this because of lack of information and there is nothing we can do at this point, but feel free to add more information and I can reopen the issue. Usually if you clear cookies and start again it should work.

**Closed by phy25** 2020-01-19 18:27 UTC
Labels: requires more info

**Comment by Klap-in** [comment] 2020-01-19 22:26
I’m wondering whether this is related to cookies. What is the authentication plugin you are using? Are there any ACL settings? Is this media manager the fullscreen version or the pop-up version? Is this at top level or in a namespace?

**Comment by micgro42** [comment] 2020-01-19 22:58
> I’m wondering whether this is related to cookies. What is the authentication plugin you are using? Are there any ACL settings? Is this media manager the fullscreen version or the pop-up version? Is this at top level or in a namespace?

That would be the popup. If I'm not mistaken, then the fullscreen version doesn't have the existing files in the same view as the upload interface.

Though the problem is curious indeed. The permission handling should be independent of the browser being used. And if there would be problems with our cookies on chrome, then I would expect many more issues about that. I'm somewhat at a loss for coming up with a theory where login as admin works, but uploading doesn't, but only in Chrome. :/

**Comment by micgro42** [comment] 2020-01-19 23:03
Maybe https://github.com/splitbrain/dokuwiki/blob/65fda485d44f1cb0f57c3adeacc0426d3f18d6d7/inc/media.php#L698 goes wrong in a weird way?

However, I cannot reproduce it
