### ISSUE TITLE
Allow sorting sitemap (index) by page title rather than filename

### ISSUE THREAD

**Issue by ClairelyClaire** [splitbrain/dokuwiki#3248] opened 2020-08-31 17:13 UTC
On one of my Dokuwiki animals, my page filenames are short, while the page title is not. I have `useheading` set to `always`, so my page headings are used for links everywhere. It makes more sense (and reads better) for the index to also sort by page heading.

This is what I have now:
![image](https://user-images.githubusercontent.com/3516276/91747211-a5e0e580-eb72-11ea-9772-2bc884c6c0d5.png)

**Comment by Michaelsy** [comment] 2020-08-31 19:28
You can use the Indexmenu Plugin instead, it is highly customizable.
https://www.dokuwiki.org/plugin:indexmenu

\- Michael Sy.

**Comment by moisesbr-dw** [comment] 2020-08-31 23:08
Duplicate of #3149.

**Comment by phy25** [comment] 2020-09-21 03:08
Closing because of duplicate. Please follow up in #3149.

**Closed by phy25** 2020-09-21 03:08 UTC
