### ISSUE TITLE
Links in the "Last changes" page are partially red and unreachable

### ISSUE THREAD

**Issue by bernhardbrunner** [splitbrain/dokuwiki#3762] opened 2022-09-05 13:46 UTC
Changed and newly created pages not by me (user with admin rights) have a different form and lead to the media manager

Working link: ''https://xyz.tld/path/phymat/mod-schwingungen/start''

Broken link, leading to media manger of the page: ''https://XZY.tld/PATH/start?tab_details=view&ns=users%3Amax.moritz%3Ablog&image=users%3Amax.moritz%3Ablog%3A2022-09-05_31.8.2022_-_auftraege_zu_hause_interferenz&do=media

From what I see, all changes by me are ok. Changes by other users (which are accessable by me because I have admin rights) are of the media manager form.

**Comment by splitbrain** [comment] 2022-09-05 13:52
duplicate of #3613

**Closed by splitbrain** 2022-09-05 13:52 UTC
