### ISSUE TITLE
No admin menu after upgrade to 2017-02-19c

### ISSUE THREAD

**Issue by scsi44** [splitbrain/dokuwiki#2074] opened 2017-08-15 04:33 UTC
Upgraded from 2017-02-19b to 2017-02-19c
using NTLDM to authenticate against active directory

After upgrade via upgrade plugin, link to admin menu in top right hand corner is not displayed anymore. I changed template (bootstrap3 to dokuwiki), but link is still not present. ACL did not change. Same error on different browsers.

**Comment by phy25** [comment] 2017-08-21 03:44
Try http://DOKUWIKI_URL/?do=check and check against `Your current permission for this page is ???`. If it is not 999, that means there's something wrong with your admin permission.

**Comment by splitbrain** [comment] 2017-08-22 16:54
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by splitbrain** [comment] 2017-08-27 10:28
closing this since no further feedback has been provided

**Closed by splitbrain** 2017-08-27 10:28 UTC
