### ISSUE TITLE
Upgrade to Hogfather - Caching not working

### ISSUE THREAD

**Issue by evmuc** [splitbrain/dokuwiki#3129] opened 2020-06-03 15:40 UTC
when using ``~~NOCACHE~~`` setting will be ignored and page will be always cached
Using ``purge=true`` is working

**Comment by splitbrain** [comment] 2020-06-03 16:24
Can you provide a test case?

**Comment by evmuc** [comment] 2020-06-03 16:51
When using phpwikify and ~~ NOCHACHE ~~ than pages will be empty (no data from php)
Calling the URL of that page with &purge=true pages are complete

**Comment by splitbrain** [comment] 2020-06-04 12:37
Can you give a list of all other installed plugins?

**Comment by evmuc** [comment] 2020-06-04 12:44
DataTables Plugin von  Giuseppe Di Terlizzi
Dw2Pdf plugin von  Andreas Gohr and Luigi Micco
Wrap Plugin von  Anika Henke
PHP Wikify

**Comment by LarsGit223** [comment] 2020-06-07 12:23
I can re-produce the issue with the Note plugin. E.g. take the following page content:
```
~~NOCACHE~~

<note warning>This might disappear!</note>
```
The page is displayed after creating it or after saving it with a change. But if I update it (e.g. via `F5` in Firefox) than the content generated by the note plugin might disappear. It does not happen on the first update but after pressing `F5` a second or third time.

If `purge=true` is appended to the page URL, then the issue is not there.

**Comment by phy25** [comment] 2020-06-07 20:49
For @LarsGit223's test case, I got these in RC2:

```
Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 106

Warning: Use of undefined constant DOKU_LEXER_UNMATCHED - assumed 'DOKU_LEXER_UNMATCHED' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 110

Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 114

Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 106

Warning: Use of undefined constant DOKU_LEXER_UNMATCHED - assumed 'DOKU_LEXER_UNMATCHED' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 110

Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 114

Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 106

Warning: Use of undefined constant DOKU_LEXER_UNMATCHED - assumed 'DOKU_LEXER_UNMATCHED' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 110

Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in \dokuwikirc\lib\plugins\note\syntax.php on line 114
```

**Comment by phy25** [comment] 2020-06-07 20:50
This should have been fixed by #3132. Could we try again with that patch, or by directly using master branch to verify?

**Comment by LarsGit223** [comment] 2020-06-08 05:17
@phy25 I will test again with the master branch as soon as I got time for it and will report the results. Thanks.

**Comment by LarsGit223** [comment] 2020-06-08 18:38
@phy25 I tested with master and it seems that the problem is fixed. I tested refreshing of a normal page, a page with `~~NOCACHE~~` included and a page URL with `purge=true` appended. In all 3 cases a page using the note plugin was rendered properly after several refreshs (min. 5 refreshs).

**Comment by phy25** [comment] 2020-06-08 20:32
@LarsGit223 Thanks, going to close this.

**Closed by phy25** 2020-06-08 20:32 UTC
Labels: duplicate
