### ISSUE TITLE
pagetools disappeared

### ISSUE THREAD

**Issue by aborruso** [splitbrain/dokuwiki#1011] opened 2015-01-18 17:25 UTC
Hi,
I have an old dokuwiki version (Weatherwax, I know, tool old). After several months of use the Page Tools disappeared.

I emptied the cache, but I have the same results.

Any suggestions?

Thank you

**Comment by dom-mel** [comment] 2015-01-18 17:42
Sounds like a JavaScript error. You can have a look in your browser javascript console.

Usually the source of a JavaScript error is a plugin or custom template.

**Comment by aborruso** [comment] 2015-01-18 17:48
Hi @dom-mel , thank you.

I have only this error in javascript console "Failed to load resource: net::ERR_CACHE_MISS", and it seems to me not related to my problem. Am I wrong?

**Comment by dom-mel** [comment] 2015-01-18 18:29
Yeah it's not related to your problem. Chrome shows this error if you open the console after loading the page. Just reload the page after you open the console and look for other errors

**Comment by aborruso** [comment] 2015-01-18 18:30
Hi @dom-mel I made it and I have no errors. Thank you

**Comment by dom-mel** [comment] 2015-01-18 18:31
but the page tools are still missing?

**Comment by aborruso** [comment] 2015-01-18 18:39
I have seen it only now. For some (I think) CSS reason it's at the bottom of the page.

But it's always at the button also if I open an anonymous session in my browsers (chrome and firefox).
It's really strange 

![2015-01-18_19h35_50](https://cloud.githubusercontent.com/assets/30607/5793565/5f47c402-9f49-11e4-80a2-cb24437fdc15.png)

**Comment by aborruso** [comment] 2015-01-18 18:48
If I remove the update notification divs (like the one below), the page tools goes upward and I can use it.

![2015-01-18_19h46_28](https://cloud.githubusercontent.com/assets/30607/5793618/c94b1b5a-9f4a-11e4-9bee-7e40082fc59f.png)

**Comment by dom-mel** [comment] 2015-01-18 18:54
Ah yeah it's a known issue with the pagetools on the dokuwiki template. 
It will move downwards on some circumstances. i.e. if you go to yourwiki/dokuwiki.php?do=check.
IMHO this is fixed in the current dokuwiki version.

If updating is not an option for you: Just try to update the dokuwiki template (just copy the lib/tpl/dokuwiki folder to your lib/tpl folder). But i'm not sure if the new version of the dokuwiki template is compatible with old dokuwiki versions. But it may worth a try.

**Comment by splitbrain** [comment] 2015-02-09 15:41
The problem is not fixed in current devel. Unfortunately it's rather complicated to fix AFAIR. @selfthinker  any ideas?

**Closed** 2015-02-24 09:16 UTC
