### ISSUE TITLE
Black scree ...

### ISSUE THREAD

**Issue by Luicci42** [splitbrain/dokuwiki#1867] opened 2017-02-22 15:56 UTC
wenn I lock out, I get a black screen (dimmed to dark) with a white cross in the upper right corner.
Any problem with a javascript overlay window ?
Version 2017-02-19a

**Comment by mprins** [comment] 2017-02-22 16:01
duplicate of #1854

**Comment by Luicci42** [comment] 2017-02-22 16:18
Hi Mark,

thats right ! In the meantime I updated the galary plugin before (
actually all plugin that needed an update )
and everything is fine now !

thanks,

Luicci42

Am 22.02.2017 um 17:01 schrieb Mark Prins:

**Closed** 2017-02-22 16:29 UTC
