### ISSUE TITLE
Update notifications for release candidates

### ISSUE THREAD

**Issue by andynd** [splitbrain/dokuwiki#3722] opened 2022-07-29 14:49 UTC
Currently I get two of those notifications:

New release candidate 2 available: rc2022-06-26 "Igor". [upgrade now!](http://download.dokuwiki.org/) [52.1] [(what's this?)](http://www.dokuwiki.org/update_check)
New release candidate available: 2022-06-26 "Igor". [upgrade now!](http://download.dokuwiki.org/) [52] [(what's this?)](http://www.dokuwiki.org/update_check)

Both are for non stable versions. Please never recommend non stable updates via the update notifications.

**Comment by splitbrain** [comment] 2022-07-29 15:07
duplicate of #3186

**Closed by splitbrain** 2022-07-29 15:07 UTC
