### ISSUE TITLE
page history messed up when pagename contains a dot

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#3613] opened 2022-01-28 23:15 UTC
Hi,

I found a funny and strange bug. It's triggered by a dot in the pagename. I first noticed with the findbad.php history page. I originally thought `.php` was the cause, but any pagename with a dot shows the problem.

If you follow the `do=revisions` link, you get to a strange history page where only one link is present.  This unique link links to `?do=media`.

See this history https://www.dokuwiki.org/playground:eleph.pant?do=revisions

**Comment by ssahara** [comment] 2022-01-29 05:53
This must be bug with #3361 .  page name contains dot `.` is wrongly handled.
https://github.com/splitbrain/dokuwiki/blob/4ef5d38db53e045a81f129b29a8b886cecc38497/inc/ChangeLog/RevisionInfo.php#L35

Could I add more commit to fix this issue in #3607 ?

**Comment by splitbrain** [comment] 2022-01-29 06:58
@ssahara please open a new PR for the fix.

**Comment by TherealperO** [comment] 2022-08-04 14:15
Possible fix: https://github.com/splitbrain/dokuwiki/pull/3730

**Comment by Klap-in** [comment] 2022-08-04 14:37
Hi, it is indeed a option to look for the request parameters proposed, but probably there exceptions on this approach. 

The class modified is the abstract ChangeLog class. It is extended as MediaChangelog or PageChangeLog. So we always already know the type 
The more robust approach could probably be to set the type in the constructor of MediaChangelog and PageChangeLog, which calls also the parent constructor for the general part.

**Comment by Klap-in** [comment] 2022-08-04 16:45
RevisionInfo is filled with an array, could you check if that array contains `$info['media']`, I guessed it is there, at least it is set for the recent changes retrieved by the (global) getRecents() function. Not sure if it is set for all uses of RevisionInfo class?

**Comment by TherealperO** [comment] 2022-08-04 17:42
Yup, we both found `$info['media']. I've spent some time and came up with this https://github.com/splitbrain/dokuwiki/pull/3731

**Comment by TherealperO** [comment] 2022-08-05 16:02
This issue is now fixed with 8acc3ab and 8e8e73a to fix a minor issue with 8acc3ab.

**Comment by Klap-in** [comment] 2022-08-05 16:07
Thanks for the contribution!

**Comment by TherealperO** [comment] 2022-08-05 16:08
Glad to help!

**Closed by Klap-in** 2022-08-05 16:07 UTC

**Comment by hilliesample** [comment] 2022-11-04 15:32
I am adding this comment as it took me awhile to find this page. I was searching for "Old Revisions not working 2022-07-31a "Igor" as I didn't realize at first that it was related to the '.' in the page name. Hopefully this comment will help others find this page more easily. Thank you for the work on this issue.

**Comment by 0x46616c6b** [comment] 2022-11-13 17:16
Is it possible to have a new release with this fix in it? The issue is very confusing for users and they ask administrators if something is broken with there data at all. Would really appreciate when it would be fixed within a release. Thanks!

**Comment by bernhardbrunner** [comment] 2023-02-26 10:16
> Is it possible to have a new release with this fix in it? The issue is very confusing for users and they ask administrators if something is broken with there data at all. Would really appreciate when it would be fixed within a release. Thanks!

In the meantime you can just change the broken line 39 with the fix from https://github.com/dokuwiki/dokuwiki/commit/8acc3ab2a5c30044cead4210062c611d3559abc2:

In File inc/ChangeLog/RevisionInfo.php:

39 #            $info['mode'] = strrpos($info['id'], '.') ? 'media' : 'page';
40             $info['mode'] = $info['media'] ? 'media' : 'page';

This fixes the

**Comment by 0x46616c6b** [comment] 2023-02-26 18:02
Sorry but this is not a good practice. I don't want to patch software on my machines after a new release is published. What is the problem with releasing a new version of Dokuwiki with this bugfix? I mean this bug breaks a really important functionality in that kind of software: the page history.
