### ISSUE TITLE
Warning in changelog.php with php 7.2.4

### ISSUE THREAD

**Issue by GillesP227** [splitbrain/dokuwiki#2695] opened 2019-02-13 15:46 UTC
"**Warning: count(): Parameter must be an array or an object that implements Countable in ...\dokuwiki\inc\changelog.php on line 226**"

with "Recent Changes" (or "Derniers changements" as I use dokuwiki in french).
The recent changes are still shown normally.

Problem with php 7.2.4, no such problem with php 7.1.16 nor 5.6.35.

I had the problem with _Release 2018-04-22a "Greebo"_, updating to _Release 2018-04-22b "Greebo"_ did not fix the problem.

![warning count](https://user-images.githubusercontent.com/43492324/52723730-5649c180-2fae-11e9-9c6a-ab8bad795c48.jpg)

**Comment by phy25** [comment] 2019-02-13 17:12
Duplicate of #2440.

This is not yet released; it's in master branch only. You may want to help yourself applying the patch in the issue.

**Closed by phy25** 2019-02-13 17:12 UTC
