### ISSUE TITLE
any plan for mediawiki-style templates/macros?

### ISSUE THREAD

**Issue by mlinchitstest** [splitbrain/dokuwiki#1733] opened 2016-10-17 11:11 UTC
There used to be a [templater](https://www.dokuwiki.org/plugin:templater?s[]=templater) plugin, which no longer seems to work. It promised to deliver the same capability as `mediawiki templates`. On media wiki you can include the text from a template page in a document by `{{template|var1|var2}}`, where the variables take the place of the placeholders in the template. Templates can be written in wiki-markup and also have allow for conditionals, I think. Is there any plan to implement this powerful feature in dokuwiki? Such a feature would cover the functionality of half the existing plugins. Maybe there's a plugin that does this, which I'm not aware of? The closest I found was [textinsert](https://www.dokuwiki.org/plugin:textinsert?s[]=macro) but the syntax is kind of ugly and it does not accept wiki-text as input.

**Comment by mlinchitstest** [comment] 2016-10-17 12:06
Turns out there is already a plugin that does this called `macros`. The only problem with it is that it potentially messes up some other syntax blocks (mathjax, php etc) —but this looks like its fixable. (will look into it). Is there a reason why this is not a core feature of dokuwiki?

**Comment by Klap-in** [comment] 2016-10-17 13:39
It is challenge to built this feature with good support for stuff like caching, and probably not enough people start implementing this/have requested/hired some to do the implementation. Because the implementation for these kind of features where not great so far, it is not strange that these were not considered as bundled plugin.

On the other side, there are some alternatives for this functionality, however these are not an exact duplicate of the mediawiki approach.

Data plugin let you include a data entry block per page. (which data is also stored in a sqlite database such that is can be listed on other pages)
https://www.dokuwiki.org/plugin:data

Struct plugin is a recent new successor of the Data Plugin, but much better organized and structured.
https://www.dokuwiki.org/plugin:struct

Strata plugin has little different syntax. But it offers (not yet documented on its wiki page) an additional plugin which can use predefined templates, which are on load filled with data from data entry blocks of the Strata plugin.
https://www.dokuwiki.org/plugin:strata
the plugin for templating 
https://github.com/bwanders/dokuwiki-plugin-stratatemplatery

**Closed** 2016-10-17 14:50 UTC
Labels: Feature, won't implement

**Comment by mlinchitstest** [comment] 2016-10-17 18:17
the original [templater](https://github.com/bwanders/dokuwiki-plugin-templatery) seemed to have been a good start. Any problems with it? I am not sure if struct handles page renames—it's the first plugin to keep everything in the database contrary to the doku paradigm, so I assume once you rename, data gets delinked.

**Comment by Klap-in** [comment] 2016-10-17 20:05
I have not tested that templater. However, from @bwanders I expect something that has had some thought.
