### ISSUE TITLE
Bug in internal search

### ISSUE THREAD

**Issue by TomB2** [splitbrain/dokuwiki#1225] opened 2015-07-08 11:07 UTC
Hi

I'm using Release 2014-09-29a "Hrun".

I searched sth using the wiki internal search but the result was empty although the search string was definitly available in one page.

I searched for a text that is part of an unordered list. Don't know if that's important.

I edited that page and saved it. The wiki complained about an unsaved version and displays the diff screen. After confirming I did the same search but this time got a success.

Thanks for that great project.
Tom

**Comment by Klap-in** [comment] 2015-07-08 16:51
Please provide exact example data that let us reproduce your case.
Maybe you can write a page at dokuwiki.org which shows this issue. Thanks!

**Comment by Klap-in** [comment] 2015-07-08 20:36
Additional question: Was the page edited with an external editor before?

**Comment by TomB2** [comment] 2015-07-09 14:22
Can't reproduce the issue. Sorry.
The page was not edited by an external editor.
As there is no concurrent write access to that wiki the diff page might be the result
of a server movement.

Please close it if you also think that it is not reproducable.

**Comment by Klap-in** [comment] 2015-07-09 16:12
I get the impression that due to an unknown cause the page was not indexed (anymore). Editing has triggered an update of the index used by the search function. So after the edit you could find it by search again.

Without the cause of not indexing, it is not doable to fix. So I will close it now. If you spot other occurrences, I invite you to reopen it. Thanks for the effort.

**Closed by Klap-in** 2015-07-09 16:12 UTC
Labels: Bug, Category: Backend, Severity: Small
