### ISSUE TITLE
underscore not correctly rendered

### ISSUE THREAD

**Issue by ycollet** [splitbrain/dokuwiki#2804] opened 2019-06-18 09:07 UTC
I try to enter the following text:
```
reste du texte __test__  reste du texte
reste du texte __test_test__ reste du texte
```
The 'test_test' is not correctly rendered. The underscore is removed.

I need to enter the following text to get my underscore back:
```
reste du texte __test__  reste du texte
reste du texte __test%%_%%test__ reste du texte
```

I use 2018-04-22b "Greebo" ...

**Comment by ycollet** [comment] 2019-06-18 09:23
After some investigations, we found that the "markdowku" plugin was responsible of this.
The ckgedit plugin has mixed up the style of some pages too ...

**Comment by phy25** [comment] 2019-06-18 14:26
Since I cannot reproduce this here https://www.dokuwiki.org/playground:issue2804, I will close this.

**Closed by phy25** 2019-06-18 14:26 UTC
