### ISSUE TITLE
Can't save contents

### ISSUE THREAD

**Issue by tomtomtomtony** [splitbrain/dokuwiki#3015] opened 2020-03-17 00:31 UTC
I  input the following text into DokuWiki ,but can't save or preview it:

```
<code bash [enable_line_numbers="true"]>
.
├── 0
│   ├── epsilon
│   ├── k
│   ├── nut
│   ├── nuTilda
│   ├── omega
│   ├── p
│   └── U
├── constant
│   ├── polyMesh
│   │   ├── boundary
│   │   ├── cellZones
│   │   ├── faces
│   │   ├── faceZones
│   │   ├── neighbour
│   │   ├── owner
│   │   ├── points
│   │   └── pointZones
│   ├── transportProperties
│   └── turbulenceProperties
├── obstacle.msh
└── system
    ├── blockMeshDict
    ├── controlDict
    ├── fvSchemes
    └── fvSolution
4 directories, 22 files
</code>
```

I have test lots of times. If the last six lines are delete, all will be ok, however, when the last six lines,(i.e from system to fvSolution) be added,I can't save or preview the contents. The page will be a blank page .

I use the 2018 Greebo edition of DokuWiki-portable in windows 10, offline.

**Comment by phy25** [comment] 2020-03-17 04:52
Sounds like a server issue, and I also cannot reproduce your issue here: https://www.dokuwiki.org/playground:issue3015

What is your "DokuWiki-portable"? Could you provide a link of it, since this is definitely a third-party suite?

**Comment by Klap-in** [comment] 2020-03-17 06:43
We offer to download DokuWiki from the download page, optionally including a minimal webserver. This is for a stand-alone or usb usage. See at https://download.dokuwiki.org/ in the left bottom section.

**Comment by tomtomtomtony** [comment] 2020-03-17 16:03
> Sounds like a server issue, and I also cannot reproduce your issue here: https://www.dokuwiki.org/playground:issue3015
> 
> What is your "DokuWiki-portable"? Could you provide a link of it, since this is definitely a third-party suite?

yep, as @Klap-in said, "DokuWiki-portable" is one of the office versions.
To make things more clear, I have to make a video.
https://send.firefox.com/download/0178ae51abd69842/#IbbKRx6uGgD1EjuXjJtRnQ.
I have tried similarity operation in Edge, and also can't save. So, I think, it may be not an error of web browsers.
Thank you very much for your reply

**Comment by phy25** [comment] 2020-03-17 18:54
I see, this DokuWikiStick is maintained here: https://github.com/splitbrain/dokuwiki-stickbuilder

```
AH00428: Parent: child process exited with status 3221225725 -- Restarting.
```

https://www.codexpedia.com/apache-server/parent-child-process-exited-with-status-3221225725-restarting-on-xamp-apache/

Could you open an issue there?

**Comment by tomtomtomtony** [comment] 2020-03-18 01:09
> I see, this DokuWikiStick is maintained here: https://github.com/splitbrain/dokuwiki-stickbuilder
> 
> ```
> AH00428: Parent: child process exited with status 3221225725 -- Restarting.
> ```
> 
> https://www.codexpedia.com/apache-server/parent-child-process-exited-with-status-3221225725-restarting-on-xamp-apache/
> 
> Could you open an issue there?

Ok,I have done

**Comment by phy25** [comment] 2020-03-20 19:36
As I mentioned you can work around this by modifying the appropriate Apache setting: https://www.codexpedia.com/apache-server/parent-child-process-exited-with-status-3221225725-restarting-on-xamp-apache/

I will close the issue here but you can follow up at dokuwiki-stickbuilder issue.

**Closed by phy25** 2020-03-20 19:36 UTC
Labels: upstream
