### ISSUE TITLE
Wiki search fails if restricted to a namespace whose ID contains '-' or '.'

### ISSUE THREAD

**Issue by jscheiber** [splitbrain/dokuwiki#1659] opened 2016-08-09 11:58 UTC
Applies to:  "Detritus" and "Elenor of Tsort"
Modules: Wiki core search and searchform plugin
# Description

Namespaces containing the special the characters  '-' or '.' like
dev:releases:release_2016-04-02
or
cal:2015:date.20150801

are valid according to Wiki documentation, but when restricting search to such namespace with special characters, Wiki search and related plugins (searchform) **do not show quicksearch and full search results** e.g.:

changelog @dev:releases:release_2016-04-02

fails to show the "changelog" page in this namespace, whereas a search starting in the parent namespace

changelog @dev:releases

shows all changelogs in all sub-spaces including "release_2016-04-02"
# Why is this issue important?

Beside the general confusion of not finding things in certain areas, this bug currently prevents us from using DokuWiki as lightweight CRM, since many namespaces for e.g. actions, dates, projects, contacts, offers, etc need a unique naming convention 
- that does not conflict with the "usual" pages in knowledgbase namespaces
- and frequently requires a date identifier; but the bureaucracy plugin provides dates and creates pages with the '-' character in YYYY-MM-DD notation

e.g.:
c.contactname ... for contacts
dt.YYYY-MM-DD_datename ... for dates, meetings
a.YYYY-MM-DD_actionname, prj.projectname, wp.workpackagename, ... etc.

Most of these namespaces get automatically a sidebar that allows search within this contact / project / ... (plugin searchform).

Since the underscore is frequently used for all sort of pages, its easy to discriminate between automated CRM-pages and normal user pages, if the prefix delimiter is a "." and users are requested not to use dots in their page names.

**Comment by Klap-in** [comment] 2016-08-09 13:25
This query matches:
https://www.dokuwiki.org/start?do=search&id=second+%40playground%3Adev%3Areleases
This query matches not:
https://www.dokuwiki.org/start?do=search&id=second+%40playground%3Adev%3Areleases%3Arelease_2016-04-02


(This works fine, but is not your issue...

This finds a lot of pages in this namespace: https://www.dokuwiki.org/start?do=search&id=RSS+%40zh-tw
And this about twice that number of pages: https://www.dokuwiki.org/start?do=search&id=RSS+%40zh )

Query with part of namespace fails as well:
https://www.dokuwiki.org/start?do=search&id=fourth+%40playground%3Adev%3Arelease
This fails also: https://www.dokuwiki.org/start?do=search&id=fourth+%40playground%3Adev%3Areleases%3Arelease-moretext
fails too: https://www.dokuwiki.org/start?do=search&id=fifth+%40playground%3Adev%3Areleases%3Arelease-moretext%3Ans

**Comment by Klap-in** [comment] 2016-08-09 15:51
The query parser is `function ft_queryParser($Indexer, $query)`
https://github.com/splitbrain/dokuwiki/blob/master/inc/fulltext.php#L552

**Comment by splitbrain** [comment] 2016-08-09 16:04
Only exact namespace will work. Eg. ``@playground:dev:release`` does not work (doesn't exist) but ``@playground:dev:releases`` works (note the trailing s).

The search for the zh-tw namespace shows that the feature is generally working.

@jscheiber could there be something else interfering with your search results? Can you reproduce the problem at dokuwiki.org? Does the problem only occur when searching from the searchform plugin or from the "normal" search field in the dokuwiki template as well?

**Comment by Klap-in** [comment] 2016-08-09 16:57
Zh-tw example is wrong, because it is not searching for page name.

**Comment by jscheiber** [comment] 2016-08-09 18:14
**@splitbrain**  
### 1. Reproduction at dokuwiki.org
Only partial reproduction so far:
First, thanks for pointing me to the feature of using the dokuwiki.org playground
Namespace testing setup - using pages _page1_ and _page2_  in the main namespace and in the LOG sub-space:

- playground:jscheiber:start
- playground:jscheiber:case_2016-08-08:start  (title: TC1 - Test Case 2016-08-08)
- playground:jscheiber:case_2016-08-08:page1  (title: TC1 - Page 1)
- playground:jscheiber:case_2016-08-08:page2  (title: TC1 - Page 2)
- playground:jscheiber:case_2016-08-08:log:page1  (title: Log 1)
- playground:jscheiber:case_2016-08-08:log:page2  (title: Log 2)


Full search **works** fine with:
TC* @playground:jscheiber:case_2016-08-08
LOG @playground:jscheiber:case_2016-08-08
(finds TC and LOG strings in page titles)

It **fails** for a page name search:
page1 @playground:jscheiber:case_2016-08-08

but page name search **works** if started in parent namespace:
page1 @playground:jscheiber

The results are a bit different from our setup, since ours also fails for page names, but this could be due to configuration settings.

### 2. Searchform
The issue appears identically with searchform and the core Dokuwiki search field

### 3. Interference
Some of our configuration settings that affect search obviously differ from the dokuwiki.org settings.
E.g. quicksearch at dokuwiki.org seams not to take into account page titles, but it finds page names, ...
And we operate Dokuwiki with ~60 plugins.

**Comment by jscheiber** [comment] 2016-08-09 18:55
Added 2 more examples at Dokuwiki.org playground:

1. A namespace with a dot '.': **same issue as with '-'**
2. A namespace with only underscore delimiters: **all searches work fine**

### Namespace Example with a dot - Issue reproduced
- playground:jscheiber:spr.search:start  (title: Software Problem Report - Namespace Search)
- playground:jscheiber:spr.search:page1  (title: SPR Description)
- playground:jscheiber:spr.search:page2  (title: SPR Testing)
- playground:jscheiber:spr.search:log:page1  (title: SPR Logfile 1)
- playground:jscheiber:spr.search:log:page2  (title: SPR Logfile 2)

Searches:

1. SPR @playground:jscheiber:spr.search   **(text search is OK)**
2. page1 @playground:jscheiber:spr.search  **(page name search fails)**
3. page1 @playground:jscheiber   **(page name search works from parent directory)**


### Namespace Example with only unsderscore delimiter - everthing OK

- playground:jscheiber:spr_search_ul:start  (title: Software Problem Report 2 - Namespace Search - no special chars)
- playground:jscheiber:spr_search_ul:page1  (title: SPR Description - nochars)
- playground:jscheiber:spr_search_ul:page2  (title: SPR Testing - nochars)
- playground:jscheiber:spr_search_ul:log:page1  (title: SPR Logfile 1 - nochars)
- playground:jscheiber:spr_search_ul:log:page2  (title: SPR Logfile 2 - nochars)

Searches:

1. SPR @playground:jscheiber:spr_search_ul
2. page1 @playground:jscheiber:spr_search_ul
3. page1 @playground:jscheiber

All searches work, if namespace does not contain '.' or '-'.

**Comment by micgro42** [comment] 2018-03-23 12:32
The root cause is that the responsible regex does not account for `-` or `+`, but only for `\w` and `:`
https://github.com/splitbrain/dokuwiki/blob/81693bed0f4feedff78c111364b23b78ad979c93/inc/fulltext.php#L236

This could easily be fixed by adjusting the regex.

However, I'm wondering why we are fiddeling with regexes, when we have a [query parser](https://github.com/splitbrain/dokuwiki/blob/master/inc/fulltext.php#L552)? Or would using the query parser drain too much performance?

**Closed** 2018-04-05 07:51 UTC
Labels: Bug, Category: Backend, Needs Feedback/Discussion
