### ISSUE TITLE
Incomplete download for 2018-04-22c upgrade

### ISSUE THREAD

**Issue by mforkel** [splitbrain/dokuwiki#3109] opened 2020-05-31 09:07 UTC
A [changes file for version 2018-04-22c](https://download.dokuwiki.org/out/dokuwiki-cbd20a739c46f83c51803eea1e089a91.tgz) downloaded from [Download DokuWiki](https://download.dokuwiki.org/) with options _Download changed files only_, _Upgrade Plugin_, _Wrap Plugin_, and _de_ as its only additional language does not include the file ```inc/toolbar.php```. That file was changed in commit 98169a0fe.

As a consequence, all editor buttons to the right of _Select Headline_ are not displayed.

**Comment by phy25** [comment] 2020-06-05 04:33
I can confirm this still happens, simply by choosing *Download changed files only* and *2018-04-22c*.

https://download.dokuwiki.org/out/dokuwiki-5a92eac05a228580a4257d5e11a90c26.tgz

**Comment by Klap-in** [comment] 2020-06-05 07:08
@phy25 did you select also all/any language?

The download builder is here https://github.com/splitbrain/download.dokuwiki.org/blob/master/lib/Builder.php

@bug or @splitbrain is it worth to try to reupload a new version?

**Comment by phy25** [comment] 2020-06-05 12:42
I seem to know why... Thanks @Klap-in for posting that link.

When generating the diff for stable, it might use oldstable to compare against. Oldstable has the same patch applied, so https://download.dokuwiki.org/src/dokuwiki/stable/inc/toolbar.php is identical to https://download.dokuwiki.org/src/dokuwiki/oldstable/inc/toolbar.php and it won't be added into the patch.

Sounds like thay feature is a bit misleading, we might need to explain what it's compared against on the download page.

**Comment by phy25** [comment] 2020-06-05 12:46
I read the download page again and seems like it's intended behavior (sorry!) Closing.

**Closed by phy25** 2020-06-05 12:46 UTC
Labels: Bug

**Comment by Klap-in** [comment] 2020-06-05 13:47
@phy25, the problem of this issue is that "does not include the file inc/toolbar.php.".
You are closing, so you mean that this file is just included again?

**Comment by phy25** [comment] 2020-06-05 13:56
It's expected behavior because that patch always compares against oldstable, as is mentioned on the download page. The upgrade guide linked there stats that you need to upgrade it to the latest minor version before upgrading using patch (as I remember).

**Comment by mforkel** [comment] 2020-06-05 14:04
I misread the description on the upgrade page. Now I understand that the upgrade is in accordance with that description. I wonder  though whether there a more people upgrading from old stable than from the last minor version. How about providing an incremental upgrade for that use case?
