### ISSUE TITLE
Skip Release Candidates

### ISSUE THREAD

**Issue by SmuSmu** [splitbrain/dokuwiki#3184] opened 2020-06-22 14:30 UTC
It would be awesome to have a setting to skip release candidates in the update notification bar. On some systems I just want to migrate to the latest stable version.
Maybe using semver instead of a int value. Then it would be easy to follow new features and/or just bugfixes. Of course then there should be a EOL date of each major version.

**Comment by phy25** [comment] 2020-06-23 00:58
Duplicate of https://github.com/splitbrain/dokuwiki-plugin-upgrade/issues/189.

**Comment by phy25** [comment] 2020-06-23 01:00
Wrong reference, still duplicate... Please follow #3144.

**Closed by phy25** 2020-06-23 01:00 UTC
Labels: duplicate
