### ISSUE TITLE
Username enumeration from password reset

### ISSUE THREAD

**Issue by theotheredbaron** [splitbrain/dokuwiki#3540] opened 2021-10-04 13:36 UTC
The password reset function shows whether or not a username exists rather than just saying "If you have an account you will now get an email"

This is a really Bad Idea as it means bots can enumerate user accounts until they get one that works, then bomb the site with generic passwords until one gets in for that username.

Usual security policy for many years has been to hide usernames, and this doesn't.

Example:
username: admin - probably works in most situations, but
username: adam - quite possible, and the bots now know that's an account to try "adam123" or variants as a password without wasting time on a username that doesn't exist.

**Comment by phy25** [comment] 2021-10-04 14:35
Duplicate of #1727, #2928, #2935. Do you have anything to add to the previous conversation that had happened?

**Comment by theotheredbaron** [comment] 2021-10-04 15:16
No, but reading the previous it seems I'm not the only person concerned with this deliberate choice to reduce security.

That's fine, as (before you say it!) we can always use other software that has made a different choice :)

Thanks for your reply.  Please feel free to close - thanks.

**Closed** 2021-11-10 18:57 UTC
