### ISSUE TITLE
stable version 2017-02-19 "Frusterick Manners" with microapache does not install

### ISSUE THREAD

**Issue by aubreyz** [splitbrain/dokuwiki#1857] opened 2017-02-20 16:34 UTC
Tried several times
on Windows 10
Each time, after the page entering details for superuser next page is

Fatal error: Call to undefined function random_int() in C:\Users\Aubrey\Downloads\doku\DokuWikiStick\dokuwiki\inc\PassHash.class.php on line 630

Am aware of previous bug reports with this error but clearly this has now propagated into the latest "stick" version. 

Fresh download not an upgrade. Stable version 2017-02-19 "Frusterick Manners" with microapache and the PHP version imposed therein.

**Comment by splitbrain** [comment] 2017-02-20 17:02
duplicate of #1852

**Closed by splitbrain** 2017-02-20 17:02 UTC
