### ISSUE TITLE
Some namespaces (redirects to local wiki pages) not clickable/linked?

### ISSUE THREAD

**Issue by Espionage724** [splitbrain/dokuwiki#3506] opened 2021-06-24 08:57 UTC
- https://wiki.realmofespionage.xyz/start?do=index

> This is a sitemap over all available pages ordered by [[doku>namespaces|namespaces]].

`[[doku>namespaces|namespaces]]` specifically isn't clickable and just shows as plain-text. This happens on a few other pages as well, but seemingly only involving pages that are default to DokuWiki. Not too sure if it's related, but [wiki:dokuwiki](https://wiki.realmofespionage.xyz/wiki:dokuwiki) looks improperly formatted.

[My general DokuWiki config is listed here](https://wiki.realmofespionage.xyz/servers:nginx:dokuwiki).

**Comment by selfthinker** [comment] 2021-06-30 18:46
This might be the same as #3507

**Comment by Espionage724** [comment] 2021-07-03 01:48
I disabled PCRE JIT with `php_value[pcre.jit] = "0"` in PHP-FPM ([config](https://wiki.realmofespionage.xyz/servers:nginx:dokuwiki#php-fpm_socket)), re-saved the config from DokuWiki (reported to clear caches), and it seems like everything is fine now.

Along with some namespaces not being linked, some of my older pages had broken rendering as well (had a page back from 2018 that wasn't formatted right). After the JIT disable, the older pages render fine.

**Comment by selfthinker** [comment] 2021-07-13 20:34
Closing as it's resolved and a duplicate of #3507.

**Closed by selfthinker** 2021-07-13 20:34 UTC
