### ISSUE TITLE
"The plugin repository could not be contacted." ... "Timeout while reading response" with internal _readData() function. Works if I replace

### ISSUE THREAD

**Issue by teldri** [splitbrain/dokuwiki#1407] opened 2015-11-23 19:12 UTC
Since no one in the dokuwiki forum gave me an answer to my request I think here is the right place to ask.
The problem is the update funtion for plugins an the wiki itsself with the following message:

> The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings.

<h6>What I´ve tried to do so far:</h6>
- Server has acces to repository in general
- Tryed to en/disable proxy settings as suggested in forums
- Reproduceable on 2 different servers, tested with 3 different PHP Versions (Windows servers, Apache 2.4.xxx)
- Installed the latest version of dokuwiki

After all I got despred and started do debug in a local copy of our productive wiki. I´m runnig tThe debug process actually with PHP 5.6.14(fastCGI).

<h6>So I tracked it to this point:</h6>

`HTTPClient.php => Class HTTPClient => Function sendRequest()`
**calls**
`HTTPClient.php => Class HTTPClient => Function _readData()`
**in**
`HTTPClient.php Line 507`

`_readData()` **throws**

> Timeout while reading response (unlimited) after 1 bytes (5.266s)

<h6>It works if I replace :</h6>

```
$r_body .= $this->_readData($socket, 4096, 'response (unlimited)', true);
```

with:

```
usleep(1000);
$r_body.=fread($socket, 1024);
$stream_meta_data = stream_get_meta_data($socket);
if($stream_meta_data['unread_bytes'] <= 0) break;
```

My guess is that my problem has to do with the non-bocking stream and the stream_select function. But my knowledge regarding streams is not good enough to know that for sure. Please feel free to  blame me if it is just a wrong configuration of apache or PHP.

**Comment by splitbrain** [comment] 2015-11-28 08:51
you mention proxy settings. can you describe your exact proxy setup?

**Comment by teldri** [comment] 2015-11-28 12:04
Sorry, I didn´t mention that I don´t use a proxy in general. 
I just tryed once the "Use SSL to connect to proxy" option because someone in a forum belived that this fixed his problems even without using a proxy. I didn´t really expect it to work but I was despered and tryed everything...
So most and also the latest tests were all withoutout proxy settings.

**Comment by teldri** [comment] 2015-11-28 13:23
I´m really emabaresed that I didn´t try that before. Sorry for stealing your time.

I tested the same copy of dokuwiki at home and it works. Then I connected with VPN to my company network and got the connection problem again.

So I´ll try to figure out the problem with our central network managment on monday. If there is any result worth letting other people know, I´ll write it here.

**Comment by polyzen** [comment] 2015-11-28 13:24
The message `The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings.` often appears for me as well after opening the Extension Manager

**Comment by teldri** [comment] 2015-11-28 13:40
What do you mean with "often"?
Can you reproduce the case when it works and when it desn´t work.

- Is your server hosted in a network that uses a proxy server?
- Did you check if your antivirus software might block it?

**Comment by polyzen** [comment] 2015-11-28 14:47
Not sure how to reproduce. Just now I didn't get the message when accessing
the wiki from my lan, but I did see it after logging in via wan. The
message went away after reloading the page.

1) No proxy
2) No antivirus

**Comment by joakinen** [comment] 2016-04-11 17:23
I'm having this issue on two wikis moved to a new server (Detritus & Hrun). I've read opinions pointing to server config as the cause of the failure but without pointing the exact configuration error. Could someone help to diagnose this error? Thanks.

**Comment by teldri** [comment] 2016-04-12 12:40
@joakinen: I´m sorry I cant help you with that still I still have no clou why it´s not working.

@splitbrain: regarding my comment from "commented on 28 Nov 2015"..
Some time ago I wanted to figure out with our firewall guys if there is some kind of blocking in our network. They said that there is no blocking in our firewall or content filter proxy. The log files tell us that every communication from our dokuwiki can pass without any block.
So actually I´m out of ideas...

**Comment by Klap-in** [comment] 2016-04-18 19:42
Could it be possible that there is a relation between this issue and recently improved TLS stuff: https://github.com/splitbrain/dokuwiki/issues/1526 ?

**Comment by splitbrain** [comment] 2016-04-18 20:39
@teldri @joakinen @polyzen could you please unzip the attached PHP file into your dokuwiki directory and call it from the browser, then post the results here?

[ssltest.zip](https://github.com/splitbrain/dokuwiki/files/224760/ssltest.zip)

**Comment by teldri** [comment] 2016-04-19 09:07
Server 1: `openssl_get_cert_locations() does not exist`
Server 2: ```
Array
(
    [default_cert_file] => c:/usr/local/ssl/cert.pem
    [default_cert_file_env] => SSL_CERT_FILE
    [default_cert_dir] => c:/usr/local/ssl/certs
    [default_cert_dir_env] => SSL_CERT_DIR
    [default_private_dir] => c:/usr/local/ssl/private
    [default_default_cert_area] => c:/usr/local/ssl
    [ini_cafile] => c:/apache24/ssl/ca-bundle.pem
    [ini_capath] => c:/apache24/ssl
)

---------
default_cert_file does not exist
default_cert_dir does not exist
default_default_cert_area does not exist
```

**Comment by splitbrain** [comment] 2016-04-19 18:09
@teldri thanks for the feedback. What PHP version is Server 1 running? I assume c:/apache24/ssl/ca-bundle.pem and c:/apache24/ssl do exist on Server 2?

**Comment by teldri** [comment] 2016-04-19 18:28
Server 1: 

> 	Apache/2.2.8 (Win32) DAV/2 mod_ssl/2.2.8 OpenSSL/0.9.8g mod_autoindex_color PHP/5.2.5 

Server 2: 

> Apache 2.4, OpenSSL/1.0.1p , PHP 5.6.14
ssl folder and ca-bundle.pem are existing.
Thanks for your help!

**Comment by splitbrain** [comment] 2016-04-19 18:41
Okay Server 1 is out. We require PHP 5.3+ for DokuWiki. The second one looks just fine and there's nothing that points to an SSL problem.

Now that I'm thinking about it... the repo API is reachable by HTTP anyway. So it can't be a SSL problem...

Can you please try to run the attached file from your DokuWiki directory?

[httptest.zip](https://github.com/splitbrain/dokuwiki/files/226589/httptest.zip)

**Comment by polyzen** [comment] 2016-04-19 20:19
[Output](https://ptpb.pw/ckxD) of ssltest.php
[Output](https://ptpb.pw/IyxV) of httptest.php

**Comment by splitbrain** [comment] 2016-04-19 20:23
@polyzen The httptest shows absolutely no errors and seems to be able to communicate fine with the repository. Do you still have problems in the extension manager?

**Comment by polyzen** [comment] 2016-04-19 20:24
I believe this is/was a sporatic issue; don't recall the last time I've seen the error :)

**Comment by teldri** [comment] 2016-04-21 06:54
OK, Server 1 I used only for crosschecking.
HTTPtest from server 2:

> connection pool 0s
> 
> Array
> (
> )
> 
> opening connection 0s
> 
> www.dokuwiki.org:80
> 
> request 0.031253099441528s
> 
> GET /lib/plugins/pluginrepo/api.php?q=dw2pdf&fmt=yaml HTTP/1.0
> Accept-encoding: gzip
> Accept: text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*
> Accept-Language: en-us
> Host: www.dokuwiki.org
> User-Agent: Mozilla/4.0 (compatible; DokuWiki HTTP Client; WINNT)
> Connection: Keep-Alive
> 
> response headers 0.12501096725464s
> 
> HTTP/1.0 200 OK
> Date: Thu, 21 Apr 2016 06:52:52 GMT
> Server: Apache
> Set-Cookie: DokuWiki=itr7v7d2k45jguuc796r18b8a0; path=/; HttpOnly
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Set-Cookie: DW68700bfd16c2027de7de74a5a8202a6f=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
> Cache-Control: must-revalidate, post-check=0, pre-check=0
> Pragma: public
> X-Robots-Tag: noindex
> Content-Type: text/yaml;charset=UTF-8
> Via: 1.0 zam2047.zam.kfa-juelich.de:80 (Cisco-WSA/8.5.3-069)
> Connection: keep-alive
> 
> Object headers 0.12501096725464s
> 
> Array
> (
>     [date] => Thu, 21 Apr 2016 06:52:52 GMT
>     [server] => Apache
>     [set-cookie] => Array
>         (
>             [0] => DokuWiki=itr7v7d2k45jguuc796r18b8a0; path=/; HttpOnly
>             [1] => DW68700bfd16c2027de7de74a5a8202a6f=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
>         )
> 
>     [expires] => Thu, 19 Nov 1981 08:52:00 GMT
>     [cache-control] => must-revalidate, post-check=0, pre-check=0
>     [pragma] => public
>     [x-robots-tag] => noindex
>     [content-type] => text/yaml;charset=UTF-8
>     [via] => 1.0 zam2047.zam.kfa-juelich.de:80 (Cisco-WSA/8.5.3-069)
>     [connection] => keep-alive
> )
>

**Comment by splitbrain** [comment] 2016-04-21 07:16
Hmm, that's all? Very weird. You can connect, you get response headers but no body. I notice there's a via header in the response. Some proxy seems to be between you and the server. In an earlier answer you said you're not using a proxy. It might be a transparent proxy. Unfortunately I have no indication what's going wrong there.

How long does the script run when you try it? Less than a second or more like 25 seconds?

**Comment by teldri** [comment] 2016-04-21 07:26
Hmm, ok. In one earlier post I replyed thatwe have a proxy but our network guys said that the proxy is not blocking anything. So I think I have to discuss with them again.
How should the missing body look like? So we he have a point to hang on for research.

The sxcript executes something like 15 seconds. Too short for PHP timeout and to long to be normal I think.

**Comment by splitbrain** [comment] 2016-04-21 07:34
@teldri look at the response @polyzen posted above. That's how it should look like.

15 seconds is the default timeout in the HTTPClient (I misremembered). So it seems to be a timeout indeed.

I attached a new version of the debug script that should help us to inspect what happened.

[httptest.zip](https://github.com/splitbrain/dokuwiki/files/229378/httptest.zip)

**Comment by teldri** [comment] 2016-04-21 07:59
Oh yes of course I didn´t remember that he also replyed a httptest result.

connection pool 0s

Array
(
)

opening connection 0s

www.dokuwiki.org:80

request 0.015628099441528s

GET /lib/plugins/pluginrepo/api.php?q=dw2pdf&fmt=yaml HTTP/1.0
Accept-encoding: gzip
Accept: text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*
Accept-Language: en-us
Host: www.dokuwiki.org
User-Agent: Mozilla/4.0 (compatible; DokuWiki HTTP Client; WINNT)
Connection: Keep-Alive

response headers 0.12501788139343s

HTTP/1.0 200 OK
Date: Thu, 21 Apr 2016 07:58:49 GMT
Server: Apache
Set-Cookie: DokuWiki=d9q5cvbq8cnff55ih14od9lrl3; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Set-Cookie: DW68700bfd16c2027de7de74a5a8202a6f=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
Cache-Control: must-revalidate, post-check=0, pre-check=0
Pragma: public
X-Robots-Tag: noindex
Content-Type: text/yaml;charset=UTF-8
Via: 1.0 zam2047.zam.kfa-juelich.de:80 (Cisco-WSA/8.5.3-069)
Connection: keep-alive

Object headers 0.12501788139343s

Array
(
    [date] => Thu, 21 Apr 2016 07:58:49 GMT
    [server] => Apache
    [set-cookie] => Array
        (
            [0] => DokuWiki=d9q5cvbq8cnff55ih14od9lrl3; path=/; HttpOnly
            [1] => DW68700bfd16c2027de7de74a5a8202a6f=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly
        )

    [expires] => Thu, 19 Nov 1981 08:52:00 GMT
    [cache-control] => must-revalidate, post-check=0, pre-check=0
    [pragma] => public
    [x-robots-tag] => noindex
    [content-type] => text/yaml;charset=UTF-8
    [via] => 1.0 zam2047.zam.kfa-juelich.de:80 (Cisco-WSA/8.5.3-069)
    [connection] => keep-alive
)

object(DokuHTTPClient)#15 (27) { ["agent"]=> string(53) "Mozilla/4.0 (compatible; DokuWiki HTTP Client; WINNT)" ["http"]=> string(3) "1.0" ["timeout"]=> int(15) ["cookies"]=> array(1) { ["DokuWiki"]=> string(26) "d9q5cvbq8cnff55ih14od9lrl3" } ["referer"]=> string(0) "" ["max_redirect"]=> int(3) ["max_bodysize"]=> int(0) ["max_bodysize_abort"]=> bool(true) ["header_regexp"]=> string(0) "" ["headers"]=> array(3) { ["Accept-encoding"]=> string(4) "gzip" ["Accept"]=> string(102) "text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*" ["Accept-Language"]=> string(5) "en-us" } ["debug"]=> int(1) ["start"]=> float(1461225529.1979) ["keep_alive"]=> bool(true) ["error"]=> string(69) "Timeout while reading response (unlimited) after 2815 bytes (15.143s)" ["redirect_count"]=> int(0) ["status"]=> int(-100) ["resp_body"]=> string(0) "" ["resp_headers"]=> array(10) { ["date"]=> string(29) "Thu, 21 Apr 2016 07:58:49 GMT" ["server"]=> string(6) "Apache" ["set-cookie"]=> array(2) { [0]=> string(53) "DokuWiki=d9q5cvbq8cnff55ih14od9lrl3; path=/; HttpOnly" [1]=> string(110) "DW68700bfd16c2027de7de74a5a8202a6f=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; httponly" } ["expires"]=> string(29) "Thu, 19 Nov 1981 08:52:00 GMT" ["cache-control"]=> string(42) "must-revalidate, post-check=0, pre-check=0" ["pragma"]=> string(6) "public" ["x-robots-tag"]=> string(7) "noindex" ["content-type"]=> string(23) "text/yaml;charset=UTF-8" ["via"]=> string(55) "1.0 zam2047.zam.kfa-juelich.de:80 (Cisco-WSA/8.5.3-069)" ["connection"]=> string(10) "keep-alive" } ["user"]=> NULL ["pass"]=> NULL ["proxy_host"]=> string(0) "" ["proxy_port"]=> string(0) "" ["proxy_user"]=> string(0) "" ["proxy_pass"]=> string(0) "" ["proxy_ssl"]=> int(0) ["proxy_except"]=> string(0) "" ["boundary"]=> string(33) "---DokuWikiHTTPClient--4523452351" } time: 15

**Comment by jhol** [comment] 2017-08-28 21:45
I get this in response to httptest.php:
```
connection pool 7.7962875366211E-5s

Array
(
)

opening connection 0.00012803077697754s

www.dokuwiki.org:80
```

What does this mean?

**Comment by mrclschstr** [comment] 2018-03-20 17:28
After cherry-picking the changes mentioned in https://github.com/splitbrain/dokuwiki/issues/2270#issuecomment-371030712 I receive the `The plugin repository could not be contacted` message in the Extension Manager as well (see https://github.com/splitbrain/dokuwiki/issues/2265 as well). I'm using a proxy on port 8080. Is there a general update on this issue? Should I provide the output of the test-files as well?

**Comment by sag1** [comment] 2018-04-09 13:56
I have the same problem in my dokuwiki **The plugin repository could not be contacted**

For information, i am using proxy to connect to internet and added the dokuwiki.org/github.com for PROXY OUT 

I used the httptest.php to know where is the problem. Dokuwiki tries to connect to proxy instead of using proxy, its strange. Here is the response:

connection pool 8.9883804321289E-5s
Array
(
)
opening connection 0.00010490417480469s
BIGDATA:f4Tz$trB*@proxy-ech.itn.ftgroup:3128
object(DokuHTTPClient)#42 (27) { ["agent"]=> string(53) "Mozilla/4.0 (compatible; DokuWiki HTTP Client; Linux)" ["http"]=> string(3) "1.0" ["timeout"]=> int(15) ["cookies"]=> array(0) { } ["referer"]=> string(0) "" ["max_redirect"]=> int(3) ["max_bodysize"]=> int(0) ["max_bodysize_abort"]=> bool(true) ["header_regexp"]=> string(0) "" ["headers"]=> array(3) { ["Accept-encoding"]=> string(4) "gzip" ["Accept"]=> string(102) "text/xml,application/xml,application/xhtml+xml,text/html,text/plain,image/png,image/jpeg,image/gif,*/*" ["Accept-Language"]=> string(5) "en-us" } ["debug"]=> int(1) ["start"]=> float(1523281793.8618) ["keep_alive"]=> bool(true) ["error"]=> string(141) "Could not connect to BIGDATA:f4Tz$trB*@proxy-ech.itn.ftgroup:3128 php_network_getaddresses: getaddrinfo failed: Name or service not known (0)" ["redirect_count"]=> int(0) ["status"]=> int(-100) ["resp_body"]=> string(0) "" ["resp_headers"]=> array(0) { } ["user"]=> NULL ["pass"]=> NULL ["proxy_host"]=> string(39) "BIGDATA:f4Tz$trB*@proxy-ech.itn.ftgroup" ["proxy_port"]=> string(4) "3128" ["proxy_user"]=> string(0) "" ["proxy_pass"]=> string(0) "" ["proxy_ssl"]=> int(0) ["proxy_except"]=> string(78) "127.0.0.1,localhost,10.110.143.21,*.bigdata.intraorange,*proxy-ech.itn.ftgroup" ["boundary"]=> string(33) "---DokuWikiHTTPClient--4523452351" }

Can anybody knows the solution ?

**Comment by splitbrain** [comment] 2018-04-09 14:27
@sag1 you posted your proxy password in the debug output. I edited it out but you might want to change it.

**Comment by sag1** [comment] 2018-04-09 14:44
Thank you, i didn't notice. Any idea for the problem?

**Comment by splitbrain** [comment] 2018-04-09 14:45
@sag1 your config is wrong. You put user and password into the proxy_host config. It belongs into the user and pass settings.

**Comment by sag1** [comment] 2018-04-09 14:50
Yes, now it works. Thank you for your quick support 👍

**Comment by phy25** [comment] 2020-03-09 05:22
I am going to close this since it's untouched for a long time (and does not seem to occur again). Probably new issues can be created if it's not resolved.

**Closed by phy25** 2020-03-09 05:22 UTC
Labels: Bug, Category: Backend, Needs Research, requires more info
