### ISSUE TITLE
related to website docuwiki.org // sending mail to some subscriber fails

### ISSUE THREAD

**Issue by luffah** [splitbrain/dokuwiki#3036] opened 2020-04-04 17:22 UTC
On  [groupmail  plugin](https://www.dokuwiki.org/plugin:groupmail) page, and others. If i edit and save the  page: i got an alert message that says some emails doesn't exist with format ``user@server.com,```.  However i test some mails with a mailchecker and it seems to exists.

The issue seems related to the treatment of an user list of this kind ```user1@serv.com,user2@serv.com,```.  `mail.php` in DokuWiki take as well 1) array list and 2) as string with comma separators. Could it be some issue with the 2nd one ?

I encountered similar issue with greebo - groupmail plugin while sending emails.

**Comment by phy25** [comment] 2020-04-04 17:25
Reference: #3014

**Comment by phy25** [comment] 2020-04-04 17:28
Could you provide a reproducible step when you use plugin:groupmail and probably create an issue on the plugin end as well?

**Comment by tormec** [comment] 2020-04-04 18:58
Today I had the same issue making some edits to a plugin page in DW. I've just tried to see if it happens again but seems to be not easily reproducible.

**Comment by phy25** [comment] 2020-04-04 18:59
If you are talking about dokuwiki.org, please check the mailing list link in #3014.

**Comment by tormec** [comment] 2020-04-04 19:11
I cannot add more of what as been said in the ML, but I'd like to say regarding this point:

> check the accounts of these addresses and and maybe delete them in the forum database (or try to fix the addresses where obvious)

that, in my case, the mail address is correct

**Comment by phy25** [comment] 2020-04-04 19:14
I am not sure if yours have a comma after the email. If yes, I don't think it's valid.

**Comment by luffah** [comment] 2020-04-04 21:28
> Today I had the same issue making some edits to a plugin page in DW. I've just tried to see if it happens again but seems to be not easily reproducible.

I already reported the issue for groupmail https://github.com/POpus/dokuwiki-groupmail/issues/11 , and fixed the problem on my fork by remplacing string separated by ',' with arrays in fields to, cc, bcc.

**Comment by phy25** [comment] 2020-05-25 02:13
Closing this because it should have been addressed in #3061.

**Closed by phy25** 2020-05-25 02:13 UTC
Labels: Category: DokuWiki.org
