### ISSUE TITLE
No permission to edit page after wiki migration

### ISSUE THREAD

**Issue by TaylorHere** [splitbrain/dokuwiki#2525] opened 2018-10-11 03:51 UTC
网站迁移，我把整个文件打包到新服务器，出现编辑内容没有权限，修改权限组时提示
Writing /www/wwwroot/wiki/conf/acl.auth.php failed  导致没有权限修改wiki信息  
另外尝试从服务器中 sudo vim acl.auth.php   把@ALL____8   并保存  发现仍然没有效果  请问如何解决迁移后的权限问题

**Comment by phy25** [comment] 2018-10-11 04:06
Literal translations: I zipped all old files and unzipped them on the new server when doing migration. When I edited on the new wiki it said there is no permission. When I tried to modify acl it failed because  `Writing /www/wwwroot/wiki/conf/acl.auth.php failed`. I also tried `sudo vim acl.auth.php` and manually modified it to `@ALL 8`, and it still doesn't work.

Please read on (请阅读) https://www.dokuwiki.org/install:permissions . If you still need help please reply.

**Comment by TaylorHere** [comment] 2018-10-11 06:03
> 直译：在进行网站迁移时，我将所有旧文件压缩并在新服务器上解压缩。当我在新维基上编辑时，它表示没有许可。当我试图修改acl时失败了，因为 `Writing /www/wwwroot/wiki/conf/acl.auth.php failed`。我也试过`sudo vim acl.auth.php`并手动修改它`@ALL 8`，它仍然无法正常工作。
> 
> 请阅读（请阅读）https://www.dokuwiki.org/install:permissions。如果您仍然需要帮助请回复，因为这似乎更像一个使用问题（如有疑问请回复，这应该是使用过程中文件权限的问题）。

我尝试给wiki文件777权限，并给权限组设置了delete权限 仍然无法编辑，页面提示是：“本页是唯读的，您可以看到原始码，但不能更动它。您如果觉得它不应被锁上，请询问管理员”。从您给到的URL中并未找到有价值的提示。

**Comment by phy25** [comment] 2018-10-11 06:16
Firstly since you cannot write acl file by PHP you can try to fix that. Secondly please post your acl.auth.php file here, also post the result of `?do=check` after your problematic URL and see whether the permission and logged user is right. (首先你看到了 PHP 不能写文件的提示，所以你可以试着修复文件权限。然后请把你的 acl.auth.php 发上来，另外在有问题的页面 URL 后加上 `?do=check`，把结果发上来，可以看到页面权限和登录用户是否正确。）

Also English is prefered, thanks. (另外请尽量避免在这里重复发布中文，比如我帮你翻译了一遍的英文又被翻译回了中文。否则会影响其他国际用户的阅读，谢谢。)

**Comment by TaylorHere** [comment] 2018-10-11 06:31
Thank you for your answer, my acl.auth.php file # <?php exit()?>
 #Don't modify the lines above
#Access Control Lists
# Auto-generated by install script
# Date: Tue, 31 Jul 2018 03:40:14 +0000
* @ALL 16
* @user 255
According to your prompt, add ?do=check after the problematic URL to get a prompt: "Action unknown: editdocheck" Sorry for the language barrier that interferes with reading

**Comment by TaylorHere** [comment] 2018-10-11 06:32
Thank you for your answer, my acl.auth.php file # <?php exit()?>
##Don't modify the lines above
##Access Control Lists
## Auto-generated by install script
# #Date: Tue, 31 Jul 2018 03:40:14 +0000
* @ALL 16
* @user 255
According to your prompt, add ?do=check after the problematic URL to get a prompt: "Action unknown: editdocheck" Sorry for the language barrier that interferes with reading

**Comment by TaylorHere** [comment] 2018-10-11 06:33
![image](https://user-images.githubusercontent.com/12156543/46784922-95e37100-cd62-11e8-816c-dc1a331b29d8.png)

**Comment by TaylorHere** [comment] 2018-10-11 06:34
> Firstly since you cannot write acl file by PHP you can try to fix that. Secondly please post your acl.auth.php file here, also post the result of `?do=check` after your problematic URL and see whether the permission and logged user is right. (首先你看到了 PHP 不能写文件的提示，所以你可以试着修复文件权限。然后请把你的 acl.auth.php 发上来，另外在有问题的页面 URL 后加上 `?do=check`，把结果发上来，可以看到页面权限和登录用户是否正确。）
> 
> Also English is prefered, thanks. (另外请尽量避免在这里重复发布中文，比如我帮你翻译了一遍的英文又被翻译回了中文。否则会影响其他国际用户的阅读，谢谢。)

Thank you for your answer, my acl.auth.php file 
![image](https://user-images.githubusercontent.com/12156543/46784958-c1665b80-cd62-11e8-87b2-ca1a205f5627.png)

According to your prompt, add ?do=check after the problematic URL to get a prompt: "Action unknown: editdocheck" Sorry for the language barrier that interferes with reading

**Comment by TaylorHere** [comment] 2018-10-11 07:33
&do=check  Get prompted   ![image](https://user-images.githubusercontent.com/12156543/46787707-f1b1f800-cd6a-11e8-897f-819b7957e40a.png)

**Comment by splitbrain** [comment] 2018-10-11 16:34
@phy25 thanks for helping out with the language.

@TaylorHere please stick to English in the issue tracker. However this seems not to be about a bug or feature request so it would be better suited for the forum (we have a Chinese subforum). I am closing this issue.

**Closed by splitbrain** 2018-10-11 16:34 UTC

**Comment by phy25** [comment] 2018-10-11 17:15
@TaylorHere If you still need help, feel free to email me or telegram me in Chinese (on my GitHub profile page). Again according to your `do=check` result, file permission on your server is absolutely wrong, which is why you cannot edit pages. This is not a bug, and you still need to fix it according to https://www.dokuwiki.org/install:permissions.

如果你还需要帮助的话可以用中文发邮件或者 Telegram 联系我（邮件地址见 GitHub 资料页），因为我还没有看中文论坛的习惯 😂。根据 `do=check` 的结果，你服务器上的文件权限有问题导致页面无法修改，这不是 BUG，还是得跟着 https://www.dokuwiki.org/install:permissions 做修复的。
