### ISSUE TITLE
Title change does not take effect until you change it twice.

### ISSUE THREAD

**Issue by labrat1984** [splitbrain/dokuwiki#2717] opened 2019-03-09 03:38 UTC
When I alter the title of my site in configuration settings Basic > Wiki Title and save the changes, the title change is not reflected on the site until I change the title again.  In other words, I change the title and save.  Nothing happens (even after refresh).  I change the title again and save.  The **first** change is now displayed as the title.  Looks like a bug to me.  I found no other instances where this was reported here.

I am using a more or less default installation of DokuWiki (latest version).  I have installed a MathJax extension, Markdown extension, Color extension, Remove Irrelevant Entries extension and Archive extension.  No templates.  Nothing else.

I thought you would want to know.

**Comment by phy25** [comment] 2019-03-09 03:43
What's the PHP version? What OS do you run PHP on? Do you have opcache on? Looks like #2369 to me.

**Comment by Klap-in** [comment] 2019-03-09 08:39
1. Save the configuration Manager another time.
2. Dokuwiki caches some files, could be refreshed by adding &purge=1 or ?purge=1 to url.
3. Further refresh browser cache with key combinations Ctrl+R5, or Ctrl+F5
I hope I have mentioned now all caches.

**Comment by splitbrain** [comment] 2019-03-30 20:30
I cannot reproduce it, but it might be related to the opcache. This will be fixed when #2358 is merged.

**Closed by splitbrain** 2019-03-30 20:30 UTC
