### ISSUE TITLE
Large document and preview

### ISSUE THREAD

**Issue by mclei-asw** [splitbrain/dokuwiki#2108] opened 2017-09-01 08:26 UTC
When editing large document, it is very annoying to use "Preview" to check the document, because you will lose the current cursor position.

Could there be any solution to do the Preview using Javacript async request without altering current memo box with edited source or some solution to do the preview in other tab?

**Comment by splitbrain** [comment] 2017-09-01 14:07
This is a duplicate of #815

**Closed by splitbrain** 2017-09-01 14:07 UTC
Labels: Doku Beginner's project, Feature
